"""
prose_numbers.py — every number quoted in prose, generated from the analysis files.

Tables are generated by make_tables.py; the numbers in running text are
generated here. Markdown carries inline markers that are invisible when
rendered,

    rallies pass 1,500 steps at <!-- n:ref_t_internal -->104,200<!-- /n --> games

and make_tables.py rewrites what sits between them, exactly as it does for
tables: `--check` fails if a marker is stale or names a number nothing here
defines. paper/numbers.tex receives the same values as LaTeX macros
(ref_t_internal -> \\nRefTInternal), so README, write-up and paper cannot
disagree.

Each definition says which analysis files it reads, so make_tables.py can
verify their provenance before trusting the number.

    python prose_numbers.py    # print every number with its definition
"""

import glob
import json
import os
import warnings

import numpy as np

import stats_utils as su

MATRIX = "results/matrix"

# Literature constant, not a result of this study: Ha's published score for
# the same GA at the same budget (slimevolleygym TRAINING.md, 1,000 episodes).
HA_PUBLISHED = 0.353

# readable names for conditions quoted in prose
FAMILY_LABEL = {"control": "2020 GA", "ga2015": "generational GA",
                "es": "self-play ES", "hof-eval-v2": "archive-as-test"}

# A two-population run ends in runaway dominance when one side wins more than
# this share of the cross-population games over the last 50,000 games.
RUNAWAY = 0.9
# ... measured over the last this-many checkpoints (as in make_tables table 10)
ASYM_LAST = 10


def _f(x, nd=2, sign=False):
    return f"{{:{'+' if sign else ''}.{nd}f}}".format(x)


def _games(x):
    return f"{int(x):,}"


def _frac(a, b):
    return f"{a}/{b}"


def _sig(x, nd=2):
    """A small number (a p-value) to nd significant digits, never in
    exponent notation."""
    return np.format_float_positional(x, precision=nd, unique=False, fractional=False,
                                      trim="-")


def _pct(x, nd=0):
    return f"{100 * x:.{nd}f}"


def _rows(per_run, cond):
    return [v for v in per_run.values() if v["condition"] == cond]


def _asym():
    """Outcome of every two-population run, read from the raw files."""
    runs = {}
    for f in sorted(glob.glob(os.path.join(MATRIX, "asym*_s*.npz"))):
        base, seed = os.path.basename(f)[:-4].rsplit("_s", 1)
        cond, side = base.rsplit("-", 1)
        runs.setdefault(cond, {}).setdefault(seed, {})[side] = np.load(f)
    out = {}
    for cond, seeds in runs.items():
        rows = []
        for seed, s in sorted(seeds.items()):
            ka = "strong" if "strong" in s else "a"
            kb = "weak" if "weak" in s else "b"
            if ka not in s or kb not in s:
                continue
            # cross-population win rate of the first (larger) side over the
            # last 50,000 games, and the best member of each pool at the end
            rows.append({"seed": int(seed),
                         "winrate": float(s[ka]["a_winrate"][-ASYM_LAST:].mean()),
                         "best_a": float(s[ka]["pop_best"][-1]),
                         "best_b": float(s[kb]["pop_best"][-1])})
        out[cond] = rows
    return out


# --------------------------------------------------------------------------
# Each entry: key -> (function of the loaded analysis files, files it reads,
# one-line definition). Keys use letters and underscores only, because they
# become LaTeX macro names.
# --------------------------------------------------------------------------
def definitions():
    D = {}

    def add(key, deps, doc):
        def deco(fn):
            D[key] = (fn, deps, doc)
            return fn
        return deco

    # ---- C1: the reference run -------------------------------------------
    add("ref_t_internal", ["reference"],
        "reference run: first game count at which self-play rallies exceed "
        "1,500 steps")(lambda d: _games(d["reference"]["t_internal"]))
    add("ref_t_parity", ["reference"],
        "reference run: first checkpoint scoring above 0 against the 2015 "
        "baseline")(lambda d: _games(d["reference"]["t_parity"]))
    add("ref_lag", ["reference"],
        "reference run: games between the two transitions")(
        lambda d: _games(d["reference"]["t_parity"]
                         - d["reference"]["t_internal"]))
    add("ref_peak_holdout", ["reference"],
        "reference run: best checkpoint, re-scored on the held-out seed")(
        lambda d: _f(d["reference"]["holdout"]["peak"]["mean"], 2, True))
    add("ref_final_holdout", ["reference"],
        "reference run: final checkpoint, re-scored on the held-out seed")(
        lambda d: _f(d["reference"]["holdout"]["final"]["mean"], 2, True))
    add("ha_published", [],
        "Ha (2020): published score of the same GA at the same budget "
        "(literature constant)")(lambda d: _f(HA_PUBLISHED, 2, True))

    # ---- C2: seed variance of the transition ---------------------------
    def t_int(d, which):
        v = d["conditions"]["conditions"]["control"]["t_internal"]
        return v[which]
    add("ctrl_runs", ["conditions"], "number of control seeds")(
        lambda d: str(d["conditions"]["conditions"]["control"]["n_runs"]))
    add("ctrl_t_internal_min", ["conditions"],
        "control: earliest internal transition across seeds")(
        lambda d: _games(t_int(d, "min")))
    add("ctrl_t_internal_max", ["conditions"],
        "control: latest internal transition across seeds")(
        lambda d: _games(t_int(d, "max")))
    add("ctrl_t_internal_median", ["conditions"],
        "control: median internal transition")(
        lambda d: _games(t_int(d, "median")))
    add("ctrl_t_internal_ratio", ["conditions"],
        "control: latest / earliest internal transition")(
        lambda d: _f(t_int(d, "max") / t_int(d, "min"), 1))

    def ctrl_cond(d, key, which):
        return d["conditions"]["conditions"]["control"][key][which]
    add("ctrl_t_parity_min", ["conditions"],
        "control: earliest first-above-parity checkpoint across seeds")(
        lambda d: _games(ctrl_cond(d, "t_parity", "min")))
    add("ctrl_t_parity_max", ["conditions"],
        "control: latest first-above-parity checkpoint across seeds")(
        lambda d: _games(ctrl_cond(d, "t_parity", "max")))
    add("ctrl_lag_min", ["conditions"],
        "control: shortest internal-to-external lag across seeds")(
        lambda d: _games(ctrl_cond(d, "lag_internal_to_parity", "min")))
    add("ctrl_lag_max", ["conditions"],
        "control: longest internal-to-external lag across seeds")(
        lambda d: _games(ctrl_cond(d, "lag_internal_to_parity", "max")))

    # ---- C3: transitivity --------------------------------------------------
    def within(d, cond):
        return [v for n, v in d["within"].items()
                if n.rsplit("_s", 1)[0] == cond]
    add("rho_within_ctrl", ["within"],
        "control: mean over seeds of Spearman rho(within-run Elo, training "
        "time)")(lambda d: _f(np.mean([v["spearman_elo_vs_time"]
                                       for v in within(d, "control")]), 2, True))
    add("cyclic_ctrl_pct", ["within"],
        "control: cyclic share of decided checkpoint triads, pooled, in %")(
        lambda d: _pct(sum(v["cyclic"] for v in within(d, "control"))
                       / max(1, sum(v["triads_decided"]
                                    for v in within(d, "control"))), 1))

    def learning_cyclic_max(d):
        # the largest cyclic share among conditions whose runs learned
        out = 0.0
        conds = d["conditions"]["conditions"]
        for c, a in conds.items():
            if a.get("n_reached", 0) < a["n_runs"]:
                continue
            rows = within(d, c)
            dec = sum(v["triads_decided"] for v in rows)
            if dec:
                out = max(out, sum(v["cyclic"] for v in rows) / dec)
        return out
    add("cyclic_learning_max_pct", ["within", "conditions"],
        "largest pooled cyclic share among conditions in which every run "
        "learned to rally, in %")(lambda d: _pct(learning_cyclic_max(d), 1))

    # ---- C4: the export rule ----------------------------------------------
    def proxy_rows(d):
        return [r for rows in d["proxy"].values() for r in rows]
    add("proxy_runs", ["proxy"], "control runs with population snapshots")(
        lambda d: str(len(d["proxy"])))
    add("proxy_pop", ["proxy"], "population size in the proxy check")(
        lambda d: str(proxy_rows(d)[0]["pop_size"]))
    add("proxy_rank_mean", ["proxy"],
        "mean rank of the exported individual in its own pool (1 = best), "
        "all snapshots")(lambda d: f"{np.mean([r['exported_rank'] + 1 for r in proxy_rows(d)]):.0f}")
    add("proxy_rho", ["proxy"],
        "mean Spearman rho(streak counter, score vs baseline) over snapshots")(
        lambda d: _f(np.mean([r["spearman_streak_vs_score"]
                              for r in proxy_rows(d)]), 2, True))
    add("proxy_gap", ["proxy"],
        "mean gap, best individual in the pool minus exported, points per "
        "episode")(lambda d: _f(np.mean([r["gap"] for r in proxy_rows(d)]), 2))

    def last_snap(d):
        t = max(r["tournament"] for r in proxy_rows(d))
        return [r for r in proxy_rows(d) if r["tournament"] == t]
    add("proxy_end_exported", ["proxy_heldout"],
        "final snapshot: mean held-out score of the exported individual, original runs")(
        lambda d: _f(np.mean([r["snapshots"][-1]["heldout"]["exported"]
                              for r in d["proxy_heldout"]["per_run"].values()
                              if r["group"] == "original"]), 2, True))
    add("proxy_end_above", ["proxy"],
        "final snapshot: mean number of pool members above parity")(
        lambda d: f"{np.mean([r['n_above_parity'] for r in last_snap(d)]):.0f}")

    def rx(d):
        return d["reexport"]["summary"]

    def rx_json(d):
        return d["reexport"]
    add("reexport_rec_max", ["reexport"],
        "share of the exported-to-best gap closed by the largest internal "
        "round robin, in %")(lambda d: _pct(rx(d)["recovered_fraction"][
            max(rx(d)["recovered_fraction"], key=lambda k: int(k.split("_")[1]))]))
    add("reexport_rec_sixteen", ["reexport"],
        "share of the gap closed by the 16-peer round robin, post hoc, in %")(
        lambda d: _pct(rx(d)["recovered_fraction"]["internal_16"]))
    add("reexport_games_sixteen", ["reexport"],
        "ranking games per snapshot of the 16-peer round robin")(
        lambda d: _games(rx(d)["ranking_games_per_snapshot"]["internal_16"]))
    add("reexport_peers_max", ["reexport"],
        "largest internal round robin: peers per individual")(
        lambda d: str(max(int(k.split("_")[1])
                          for k in rx(d)["recovered_fraction"])))
    add("reexport_streak_level", ["reexport"],
        "mean score of the streak-exported individual over all snapshots")(
        lambda d: _f(rx(d)["streak_score"]["level_mean"], 2, True))
    add("reexport_median_level", ["reexport"],
        "mean score of the population's median member over all snapshots")(
        lambda d: _f(rx(d)["median_score"]["level_mean"], 2, True))
    add("reexport_best_level", ["reexport"],
        "mean score of the best member (oracle) over all snapshots")(
        lambda d: _f(rx(d)["external_score"]["level_mean"], 2, True))
    add("reexport_rho_streak", ["reexport"],
        "rho(streak counter, true skill) in the re-export analysis")(
        lambda d: _f(rx(d)["rho_streak_external"], 2, True))
    add("reexport_games_max", ["reexport"],
        "ranking games per snapshot at the largest internal round robin")(
        lambda d: _games(rx(d)["ranking_games_per_snapshot"][
            max(rx(d)["ranking_games_per_snapshot"], key=lambda k: int(k.split("_")[1]))]))
    def maxkey(dct):
        return max(dct, key=lambda k: int(k.split("_")[-1]))
    add("reexport_vol_reduction_pct", ["reexport"],
        "reduction in the volatility of the reported curve, streak rule to the "
        "largest internal round robin, in %")(
        lambda d: _pct(1 - rx(d)[maxkey({k: 0 for k in rx(d)
                                         if k.startswith("internal_score_")})][
            "volatility_mean"] / rx(d)["streak_score"]["volatility_mean"]))
    def declines(d, key):
        # total fall of a series between consecutive population snapshots,
        # summed over the control runs: how much competence it 'loses'
        tot = 0.0
        for rows in rx_json(d)["per_run"].values():
            v = np.diff([r[key] for r in rows])
            tot += float(-v[v < 0].sum())
        return tot
    add("decline_exported", ["reexport"],
        "summed fall between consecutive snapshots, exported (streak) "
        "individual, all control runs")(
        lambda d: _f(declines(d, "streak_score"), 1))
    add("decline_best", ["reexport"],
        "summed fall between consecutive snapshots, best member of the pool")(
        lambda d: _f(declines(d, "external_score"), 1))
    add("decline_median", ["reexport"],
        "summed fall between consecutive snapshots, median member of the pool")(
        lambda d: _f(declines(d, "median_score"), 1))
    add("decline_ratio", ["reexport"],
        "exported individual's summed fall relative to the best member's")(
        lambda d: f"{declines(d, 'streak_score') / declines(d, 'external_score'):.0f}")
    add("reexport_rho_max", ["reexport"],
        "rho(internal margin, true skill) at the largest round robin")(
        lambda d: _f(rx(d)["rho_internal_external"][
            max(rx(d)["rho_internal_external"], key=lambda k: int(k.split("_")[1]))], 2, True))

    # ---- C5: the archive -------------------------------------------------
    def cond(d, c):
        return d["conditions"]["conditions"][c]

    def hoftest_split(d, key, learned):
        return [r[key] for r in _rows(d["per_run"], "hof-eval-v2")
                if bool(r["reached"]) == learned]
    add("hoftest_n_failed", ["per_run"],
        "archive as test: runs that never learned to rally")(
        lambda d: str(len(hoftest_split(d, "hof_winrate_late", False))))
    add("hoftest_win_late_learned_min", ["per_run"],
        "archive as test, runs that learned: lowest late archive win rate")(
        lambda d: _f(min(hoftest_split(d, "hof_winrate_late", True)), 2))
    add("hoftest_win_late_learned_max", ["per_run"],
        "archive as test, runs that learned: highest late archive win rate")(
        lambda d: _f(max(hoftest_split(d, "hof_winrate_late", True)), 2))
    add("hoftest_win_late_failed", ["per_run"],
        "archive as test, runs that never learned: mean late archive win rate")(
        lambda d: _f(np.mean(hoftest_split(d, "hof_winrate_late", False)), 2))
    add("hoftest_skip_late_learned_min", ["per_run"],
        "archive as test, runs that learned: lowest late share of games "
        "without a selection event, in %")(
        lambda d: _pct(min(hoftest_split(d, "replacements_skipped_late", True))))
    add("hoftest_skip_late_learned_max", ["per_run"],
        "archive as test, runs that learned: highest late share of games "
        "without a selection event, in %")(
        lambda d: _pct(max(hoftest_split(d, "replacements_skipped_late", True))))
    add("hoftest_t_internal_median", ["conditions"],
        "archive as test: median internal transition of the runs that learned")(
        lambda d: _games(cond(d, "hof-eval-v2")["t_internal"]["median"]))
    def vs_ctrl(d, c, metric, field):
        return d["conditions"]["vs_control"][c][metric][field]

    def reached(d, c):
        a = cond(d, c)
        return _frac(a["n_reached"], a["n_runs"])
    for key, c in (("ctrl", "control"), ("hofparent", "hof-0.25"),
                   ("hoftest", "hof-eval-v2"), ("ga", "ga2015"),
                   ("es", "es")):
        add(f"{key}_reached", ["conditions"],
            f"{c}: runs whose population ever held 1,500-step rallies")(
            (lambda c: lambda d: reached(d, c))(c))
        add(f"{key}_parity", ["conditions"],
            f"{c}: runs with at least one checkpoint above parity")(
            (lambda c: lambda d: _frac(cond(d, c)["t_parity"]["reached"],
                                       cond(d, c)["n_runs"]))(c))
        add(f"{key}_final_mean", ["conditions"],
            f"{c}: mean end-of-run champion, held out")(
            (lambda c: lambda d: _f(cond(d, c)["final_holdout"]["mean"], 2, True))(c))
        add(f"{key}_peak_mean", ["conditions"],
            f"{c}: mean best champion, held out")(
            (lambda c: lambda d: _f(cond(d, c)["peak_holdout"]["mean"], 2, True))(c))
        add(f"{key}_above_pct", ["conditions"],
            f"{c}: mean share of checkpoints above parity, in %")(
            (lambda c: lambda d: _pct(cond(d, c)["above_parity"]["mean"]))(c))

    def reached_sum(d, conds):
        cc = d["conditions"]["conditions"]
        return (sum(cc[c]["n_reached"] for c in conds if c in cc),
                sum(cc[c]["n_runs"] for c in conds if c in cc))
    add("hofparent_other_reached", ["conditions"],
        "archive as parent at p = 0.5 or with a full-run archive: runs that "
        "learned to rally, pooled")(
        lambda d: _frac(*reached_sum(d, ("hof-0.50", "hof-full"))))
    for key, c in (("sigsmall", "sigma-0.05"), ("sigbig", "sigma-0.20")):
        add(f"{key}_reached", ["conditions"],
            f"{c}: runs that learned to rally")(
            (lambda c: lambda d: reached(d, c))(c))
        add(f"{key}_vol_reached_p", ["conditions"],
            f"{c} vs control, volatility over runs that learned: exact p")(
            (lambda c: lambda d: _f(vs_ctrl(d, c, "volatility_reached",
                                            "p_two_sided"), 3))(c))
        add(f"{key}_vol_reached_delta", ["conditions"],
            f"{c} vs control, volatility over runs that learned: Cliff's delta")(
            (lambda c: lambda d: _f(vs_ctrl(d, c, "volatility_reached",
                                            "cliffs_delta"), 2, True))(c))
        add(f"{key}_above_pct", ["conditions"],
            f"{c}: mean share of checkpoints above parity, in %")(
            (lambda c: lambda d: _pct(cond(d, c)["above_parity"]["mean"]))(c))
    add("hofparent_regress_pct", ["per_run"],
        "archive as parent: share of all games that copy an archived genome "
        "back into the pool (p x archive win rate), in %")(
        lambda d: _pct(np.mean([0.25 * r["hof_archive_winrate"]
                                for r in _rows(d["per_run"], "hof-0.25")]), 1))

    def hoftest(d, key):
        return [r[key] for r in _rows(d["per_run"], "hof-eval-v2")]
    add("hoftest_win_early_min", ["per_run"],
        "archive as test: lowest per-seed archive win rate, first 50,000 games")(
        lambda d: _f(min(hoftest(d, "hof_winrate_early")), 2))
    add("hoftest_win_early_max", ["per_run"],
        "archive as test: highest per-seed archive win rate, first 50,000 games")(
        lambda d: _f(max(hoftest(d, "hof_winrate_early")), 2))
    add("hoftest_win_late_min", ["per_run"],
        "archive as test: lowest per-seed archive win rate, last 50,000 games")(
        lambda d: _f(min(hoftest(d, "hof_winrate_late")), 2))
    add("hoftest_win_late_max", ["per_run"],
        "archive as test: highest per-seed archive win rate, last 50,000 games")(
        lambda d: _f(max(hoftest(d, "hof_winrate_late")), 2))
    add("hoftest_skip_late_min", ["per_run"],
        "archive as test: lowest per-seed share of games without a selection "
        "event, last 50,000 games, in %")(
        lambda d: _pct(min(hoftest(d, "replacements_skipped_late"))))
    add("hoftest_skip_late_max", ["per_run"],
        "archive as test: highest per-seed share of games without a selection "
        "event, last 50,000 games, in %")(
        lambda d: _pct(max(hoftest(d, "replacements_skipped_late"))))

    for metric in ("final_holdout", "peak_holdout", "above_parity",
                   "late_mean"):
        short = {"final_holdout": "final", "peak_holdout": "peak",
                 "above_parity": "above", "late_mean": "late"}[metric]
        add(f"hoftest_vs_ctrl_{short}_p", ["conditions"],
            f"archive as test vs control, {metric}: exact two-sided "
            f"Mann-Whitney p")((lambda m: lambda d: _f(
                vs_ctrl(d, "hof-eval-v2", m, "p_two_sided"), 3))(metric))
        add(f"hoftest_vs_ctrl_{short}_delta", ["conditions"],
            f"archive as test vs control, {metric}: Cliff's delta")(
            (lambda m: lambda d: _f(
                vs_ctrl(d, "hof-eval-v2", m, "cliffs_delta"), 2, True))(metric))

    # ---- C6: algorithm families ----------------------------------------
    def fh(d, c):
        return [r["final_holdout"] for r in _rows(d["per_run"], c)]
    for key, c in (("ga", "ga2015"), ("es", "es"), ("hoftest", "hof-eval-v2")):
        add(f"{key}_sd_ratio", ["per_run"],
            f"{c}: s.d. across seeds of the end-of-run champion (held out), "
            f"relative to the control's")(
            (lambda c: lambda d: _f(np.std(fh(d, c), ddof=1)
                                    / np.std(fh(d, "control"), ddof=1), 1))(c))

    def sd_ratios(d):
        return [np.std(fh(d, c), ddof=1) / np.std(fh(d, "control"), ddof=1)
                for c in ("ga2015", "es", "hof-eval-v2")]
    add("family_sd_ratio_min", ["per_run"],
        "smallest endpoint s.d. ratio (vs control) among the other three "
        "families")(lambda d: _f(min(sd_ratios(d)), 1))
    add("family_sd_ratio_max", ["per_run"],
        "largest endpoint s.d. ratio (vs control) among the other three "
        "families")(lambda d: _f(max(sd_ratios(d)), 1))

    def single(d):
        return [v for v in d["per_run"].values()
                if not v["condition"].startswith("asym")]
    add("best_endpoint", ["per_run"],
        "highest end-of-run champion (held out) of any single-population run")(
        lambda d: _f(max(v["final_holdout"] for v in single(d)), 2, True))
    add("best_endpoint_condition", ["per_run"],
        "condition of that run")(
        lambda d: max(single(d), key=lambda v: v["final_holdout"])["condition"])
    add("best_endpoint_label", ["per_run"],
        "readable name of the condition with the highest endpoint")(
        lambda d: FAMILY_LABEL.get(max(single(d), key=lambda v: v["final_holdout"])[
            "condition"], max(single(d), key=lambda v: v["final_holdout"])["condition"]))
    add("ctrl_best_endpoint", ["per_run"],
        "highest end-of-run champion (held out) among control seeds")(
        lambda d: _f(max(fh(d, "control")), 2, True))

    # ---- C7: unequal power (exploratory) --------------------------------
    def A(d):
        return _asym()
    add("asym_runs", ["per_run"], "two-population runs, all conditions")(
        lambda d: str(sum(len(v) for v in A(d).values())))
    add("asym_mutual", ["per_run"],
        "two-population runs whose BOTH pools end with a member above parity")(
        lambda d: str(sum(r["best_a"] > 0 and r["best_b"] > 0
                          for v in A(d).values() for r in v)))
    add("asym_one_sided", ["per_run"],
        "two-population runs where exactly one pool ends above parity")(
        lambda d: str(sum((r["best_a"] > 0) != (r["best_b"] > 0)
                          for v in A(d).values() for r in v)))
    add("asym_neither", ["per_run"],
        "two-population runs where neither pool ends above parity")(
        lambda d: str(sum(r["best_a"] <= 0 and r["best_b"] <= 0
                          for v in A(d).values() for r in v)))

    def runaway(r):
        return r["winrate"] > RUNAWAY or r["winrate"] < 1 - RUNAWAY
    add("asym_runaway", ["per_run"],
        "two-population runs ending in runaway dominance: cross-population "
        "win rate over the last 50,000 games above 0.9 or below 0.1")(
        lambda d: str(sum(runaway(r) for v in A(d).values() for r in v)))
    add("asym_runaway_sym", ["per_run"],
        "runaways in the symmetric control")(
        lambda d: str(sum(runaway(r) for r in A(d).get("asym1x", []))))
    for key, c in (("sym", "asym1x"), ("cap", "asym2x"),
                   ("norm", "asym2x-norm")):
        add(f"asym_{key}_lead", ["per_run"],
            f"{c}: runs in which the first (larger) side wins more than half "
            f"the cross-population games at the end")(
            (lambda c: lambda d: _frac(sum(r["winrate"] > 0.5 for r in A(d)[c]),
                                       len(A(d)[c])))(c))

    def asym_cmp(d, a, b, field):
        x = [r["winrate"] for r in A(d)[a]]
        y = [r["winrate"] for r in A(d)[b]]
        return su.compare(x, y)[field]
    for key, a, b in (("norm_vs_cap", "asym2x-norm", "asym2x"),
                      ("cap_vs_sym", "asym2x", "asym1x"),
                      ("norm_vs_sym", "asym2x-norm", "asym1x")):
        add(f"asym_{key}_p", ["per_run"],
            f"final win rate of the larger side, {a} vs {b}: exact two-sided "
            f"Mann-Whitney p")((lambda a, b: lambda d: _f(
                asym_cmp(d, a, b, "p_two_sided"), 3))(a, b))
        add(f"asym_{key}_delta", ["per_run"],
            f"final win rate of the larger side, {a} vs {b}: Cliff's delta")(
            (lambda a, b: lambda d: _f(asym_cmp(d, a, b, "cliffs_delta"),
                                       2, True))(a, b))

    # ---- the compiled environment ----------------------------------------
    def v(d):
        return d["validation"]
    add("val_games", ["validation"], "paired games in the bit-level check")(
        lambda d: _games(sum(x["n"] for x in v(d)["scenarios"].values())))
    add("val_steps", ["validation"], "environment steps compared")(
        lambda d: _games(sum(x["steps"] for x in v(d)["scenarios"].values())))
    add("val_scenarios", ["validation"], "policy populations in the bit-level check")(
        lambda d: str(len(v(d)["scenarios"])))
    add("val_ref_core_hours", ["validation"],
        "core-hours for one 500,000-game run at the reference implementation's "
        "measured games per second")(
        lambda d: f"{500_000 / v(d)['reference_games_per_sec'] / 3600:.0f}")
    add("val_speedup", ["validation"],
        "compiled / reference games per second on one core")(
        lambda d: f"{v(d)['speedup']:.0f}")

    # ---- design constants ----------------------------------------------
    # Read from the code and the recorded protocol that define them, so the
    # paper cannot describe a design other than the one that ran.
    import fastvolley as fv
    import run_experiments as rx_
    from math import comb

    def design(key, doc, fn):
        add(key, [], doc)(lambda d: fn())
    design("budget", "self-play games per run", lambda: _games(rx_.TOURNAMENTS))
    design("save_every", "games between exported checkpoints",
           lambda: _games(rx_.SAVE_EVERY))
    design("n_ckpt", "checkpoints per run",
           lambda: str(rx_.TOURNAMENTS // rx_.SAVE_EVERY))
    design("pop_every", "games between population snapshots",
           lambda: _games(rx_.POP_EVERY))
    design("sweep_episodes", "episodes per checkpoint in the sweep",
           lambda: _games(rx_.SWEEP_EPISODES))
    design("select_episodes", "episodes per held-out re-score",
           lambda: _games(rx_.SELECT_EPISODES))
    design("hof_every", "games between archive entries",
           lambda: _games(rx_.HOF_EVERY))
    design("pop", "population size of the control",
           lambda: str(rx_.CONDITIONS["control"]["pop"]))
    design("sigma", "mutation scale of the control",
           lambda: str(rx_.CONDITIONS["control"]["sigma"]))
    design("init_scale", "s.d. of the initial weights",
           lambda: str(rx_.INIT_SCALE))
    design("hof_p", "probability of an archive game, main archive conditions",
           lambda: str(rx_.CONDITIONS["hof-eval-v2"]["hof_prob"]))
    design("hof_cap_full", "archive capacity spanning the whole run",
           lambda: str(rx_.CONDITIONS["hof-eval-v2"]["cap"]))
    design("long_rally", "self-play rally length that counts as learned",
           lambda: _games(rx_.LONG_RALLY))
    import analyze_matrix as am
    design("late_window", "games in the late window of every metric",
           lambda: _games(am.WINDOW * rx_.SAVE_EVERY))
    design("hof_window", "games over which early and late archive win rates "
           "are averaged", lambda: _games(am.HOF_WINDOW))
    design("asym_window", "games over which the final cross-population win "
           "rate is averaged", lambda: _games(ASYM_LAST * rx_.SAVE_EVERY))
    design("param_count", "parameters of the evolved policy",
           lambda: str(fv.PARAM_COUNT))
    design("obs_size", "observation size", lambda: str(fv.OBS_SIZE))
    design("lives", "lives per side", lambda: str(fv.MAXLIVES))
    design("t_limit", "episode step limit", lambda: _games(fv.T_LIMIT))
    import asymmetric as az
    design("n_act", "buttons (network outputs)", lambda: str(az.N_ACT))
    design("hidden", "hidden units per layer, standard network",
           lambda: str(next(h for h in range(1, az.MAX_H + 1)
                            if az.param_count(h) == fv.PARAM_COUNT)))
    add("hidden_large", ["per_run"], "hidden units per layer, larger network")(
        lambda d: str(int(np.load(sorted(glob.glob(os.path.join(
            MATRIX, "asym2x-strong_s*.npz")))[0])["hidden"][0])))
    C = rx_.CONDITIONS
    design("ga_pop", "generational GA: population", lambda: str(C["ga2015"]["pop"]))
    design("ga_opponents", "generational GA: games per individual per generation",
           lambda: str(C["ga2015"]["n_opponents"]))
    design("ga_elite_pct", "generational GA: share retained per generation, in %",
           lambda: _pct(C["ga2015"]["n_elite"] / C["ga2015"]["pop"]))
    design("es_candidates", "self-play ES: mirrored perturbations per iteration",
           lambda: str(C["es"]["pop"]))
    design("sigma_small", "mutation-scale sweep: smaller sigma",
           lambda: _f(C["sigma-0.05"]["sigma"], 2))
    design("sigma_big", "mutation-scale sweep: larger sigma",
           lambda: _f(C["sigma-0.20"]["sigma"], 2))
    design("sigma_ctrl", "control sigma, two decimals",
           lambda: _f(C["control"]["sigma"], 2))
    design("pop_small", "population sweep: smaller population",
           lambda: str(C["pop-32"]["pop"]))
    design("pop_big", "population sweep: larger population (defined, never run)",
           lambda: str(C["pop-512"]["pop"]))
    design("seeds_main", "seeds of the conditions that carry a claim",
           lambda: str(len(rx_.SEEDS_MAIN)))
    design("min_p_six", "smallest attainable two-sided exact p with six runs "
           "a side", lambda: _f(2 / comb(12, 6), 3))
    design("runaway_cut", "win rate beyond which a two-population run is a "
           "runaway (and its complement)", lambda: _f(RUNAWAY, 1))
    design("runaway_pct", "runaway cut as a percentage of games",
           lambda: _pct(RUNAWAY))

    def runs_per_condition(d):
        n = {}
        for v in d["per_run"].values():
            c = v["condition"]
            c = c.rsplit("-", 1)[0] if c.startswith("asym") else c
            n.setdefault(c, set()).add(v["seed"])
        return [len(x) for x in n.values()]
    add("runs_min", ["per_run"], "fewest runs of any analysed condition")(
        lambda d: str(min(runs_per_condition(d))))
    add("runs_max", ["per_run"], "most runs of any analysed condition")(
        lambda d: str(max(runs_per_condition(d))))
    add("pop_small_runs", ["per_run"], "runs of the smaller population")(
        lambda d: str(len(_rows(d["per_run"], "pop-32"))))
    add("asym_param_large", ["per_run"], "parameters of the larger network")(
        lambda d: str(max(int(np.load(f)["param_count"][0]) for f in
                          glob.glob(os.path.join(MATRIX, "asym2x-strong_s*.npz")))))
    add("asym_cross", ["per_run"], "share of games crossing populations")(
        lambda d: str(float(np.load(sorted(glob.glob(os.path.join(
            MATRIX, "asym1x-a_s*.npz")))[0])["cross_prob"][0])))
    add("reexport_budget_pct", ["reexport"],
        "largest ranking budget as a share of one run's games, in %")(
        lambda d: _f(100 * max(rx(d)["ranking_games_per_snapshot"].values())
                     / rx_.TOURNAMENTS, 1))

    # ---- the reference run in detail --------------------------------------
    def hold(d, tag):
        return d["reference"]["holdout"][tag]
    for tag in ("final", "peak"):
        for k, field in (("win", "win"), ("tie", "tie"), ("loss", "loss")):
            add(f"ref_{tag}_{k}_pct", ["reference"],
                f"reference run, {tag} checkpoint held out: share of episodes "
                f"{k}, in %")((lambda t, f: lambda d: _pct(hold(d, t)[f]))(tag, field))
    add("ref_peak_t", ["reference"], "reference run: games at the best checkpoint")(
        lambda d: _games(hold(d, "peak")["tournament"]))
    add("ref_above_ckpt", ["reference"],
        "reference run: checkpoints above parity on the sweep, of all")(
        lambda d: _frac(int((np.array(d["reference"]["mean_score"]) > 0).sum()),
                        len(d["reference"]["mean_score"])))

    # ---- does the swing damp? (control, 100,000-game windows) -------------
    def windows(d):
        rows = [v["window_profile"] for v in d["per_run"].values()
                if v["condition"] == "control"]
        out = []
        for i in range(min(len(r) for r in rows)):
            ws = [r[i] for r in rows]
            out.append({"sd": np.mean([w["sd"] for w in ws]),
                        "mean": np.mean([w["mean"] for w in ws]),
                        "above": sum(w["above"] for w in ws),
                        "n": sum(w["n"] for w in ws)})
        return out
    add("window_sd_first", ["per_run"],
        "control: within-run s.d. of checkpoint scores, first window")(
        lambda d: _f(windows(d)[0]["sd"], 2))
    add("window_sd_last", ["per_run"],
        "control: within-run s.d. of checkpoint scores, last window")(
        lambda d: _f(windows(d)[-1]["sd"], 2))
    add("window_sd_min", ["per_run"], "control: smallest window s.d.")(
        lambda d: _f(min(w["sd"] for w in windows(d)), 2))
    add("window_sd_max", ["per_run"], "control: largest window s.d.")(
        lambda d: _f(max(w["sd"] for w in windows(d)), 2))
    add("window_level_first", ["per_run"], "control: mean score, first window")(
        lambda d: _f(windows(d)[0]["mean"], 2, True))
    add("window_level_last", ["per_run"], "control: mean score, last window")(
        lambda d: _f(windows(d)[-1]["mean"], 2, True))
    add("window_above_first", ["per_run"],
        "control: checkpoints above parity, first window")(
        lambda d: _frac(windows(d)[0]["above"], windows(d)[0]["n"]))
    add("window_above_last", ["per_run"],
        "control: checkpoints above parity, last window")(
        lambda d: _frac(windows(d)[-1]["above"], windows(d)[-1]["n"]))

    # ---- the cross-run tournament ---------------------------------------
    def elo(d, c):
        a = d["across"]
        return [e for n, e in zip(a["runs"], a["elo"])
                if n.rsplit("_s", 1)[0] == c]
    add("across_n", ["across"], "final champions in the cross-run tournament")(
        lambda d: str(len(d["across"]["runs"])))
    add("across_cyclic_pct", ["across"],
        "cross-run tournament: cyclic share of decided triads, in %")(
        lambda d: _pct(d["across"]["cyclic"] / max(1, d["across"]["triads_decided"]), 1))
    for key, c in (("ctrl", "control"), ("hoftest", "hof-eval-v2"),
                   ("ga", "ga2015"), ("es", "es"), ("sigsmall", "sigma-0.05")):
        add(f"elo_median_{key}", ["across"], f"{c}: median Elo of final champions")(
            (lambda c: lambda d: _f(np.median(elo(d, c)), 0, True))(c))
        add(f"elo_worst_{key}", ["across"], f"{c}: lowest Elo of its final champions")(
            (lambda c: lambda d: _f(min(elo(d, c)), 0, True))(c))
    add("elo_worst_others_max", ["across"],
        "highest of the worst-champion Elos among generational GA, ES and archive "
        "as test")(lambda d: _f(max(min(elo(d, c)) for c in
                                    ("ga2015", "es", "hof-eval-v2")), 0, True))

    # ---- mutation scale and population size --------------------------------
    add("ctrl_vol_all", ["conditions"], "control: mean volatility, all runs")(
        lambda d: _f(cond(d, "control")["volatility"]["mean"], 2))
    add("sigbig_vol_all", ["conditions"],
        "sigma 0.20: mean volatility over all runs (failed run included)")(
        lambda d: _f(cond(d, "sigma-0.20")["volatility"]["mean"], 2))
    add("popsmall_reached", ["conditions"], "population 32: runs that learned")(
        lambda d: reached(d, "pop-32"))

    # ---- the 2015 baseline --------------------------------------------
    design("baseline_params", "parameters of the 2015 baseline policy",
           lambda: str(fv.BASELINE_WEIGHT.size + fv.BASELINE_BIAS.size))
    design("baseline_inputs", "inputs of the 2015 baseline policy",
           lambda: str(fv.BASELINE_WEIGHT.shape[1]))
    design("baseline_game_inputs", "game observations the baseline reads",
           lambda: str(fv.BASELINE_WEIGHT.shape[1] - fv.BASELINE_WEIGHT.shape[0]))

    # ---- compiled continuations of the reference snapshot ----------------
    def cont(d):
        r = d["resume"]
        out = [float(np.mean(np.array(x["mean_score"]) > 0)) for x in r["runs"].values()]
        return out
    add("resume_n", ["resume"], "compiled continuations of the reference snapshot")(
        lambda d: str(len(d["resume"]["runs"])))
    add("resume_snapshot", ["resume"], "games at the continued snapshot")(
        lambda d: _games(d["resume"]["snapshot_tournament"]))
    add("resume_games", ["resume"], "games added by each continuation")(
        lambda d: _games(d["resume"]["tournaments"]))
    add("resume_above_min", ["resume"],
        "compiled continuations: lowest share of checkpoints above parity, in %")(
        lambda d: _pct(min(cont(d))))
    add("resume_above_max", ["resume"],
        "compiled continuations: highest share of checkpoints above parity, in %")(
        lambda d: _pct(max(cont(d))))

    def ref_cont(d):
        t = np.array(d["reference"]["tournament"])
        sc = np.array(d["reference"]["mean_score"])
        return float(np.mean(sc[t > d["resume"]["snapshot_tournament"]] > 0))
    add("ref_cont_above", ["resume", "reference"],
        "reference continuation over the same games: share of checkpoints above "
        "parity, in %")(lambda d: _pct(ref_cont(d)))

    # ---- WP7: stronger yardsticks (slimevolleygym zoo) --------------------
    def zoo(d, opp):
        return {n: v[opp]["mean"] for n, v in d["yardsticks"]["per_run"].items()}

    def zoo_base(d):
        return {n: d["per_run"][n]["final_holdout"] for n in d["yardsticks"]["per_run"]}
    for key, opp, what in (("ga", "zoo-ga", "zoo GA"), ("cma", "zoo-cma", "zoo CMA-ES")):
        add(f"zoo_{key}_vs_base", ["yardsticks"],
            f"{what} against the 2015 baseline, points per episode")(
            (lambda o: lambda d: _f(d["yardsticks"]["zoo_vs_baseline"][o]["mean"],
                                    2, True))(opp))
        add(f"zoo_beat_{key}", ["yardsticks"],
            f"final champions scoring above 0 against the {what}")(
            (lambda o: lambda d: str(sum(x > 0 for x in zoo(d, o).values())))(opp))
        add(f"zoo_rho_base_{key}", ["yardsticks", "per_run"],
            f"Spearman rho over final champions: score vs 2015 baseline (held "
            f"out) against score vs the {what}")(
            (lambda o: lambda d: _f(su.spearman(
                [zoo_base(d)[n] for n in sorted(zoo(d, o))],
                [zoo(d, o)[n] for n in sorted(zoo(d, o))]), 2, True))(opp))
        add(f"zoo_above_beat_{key}", ["yardsticks", "per_run"],
            f"final champions above parity against the 2015 baseline that also "
            f"score above 0 against the {what}")(
            (lambda o: lambda d: str(sum(zoo(d, o)[n] > 0 for n, v in zoo_base(d).items()
                                         if v > 0)))(opp))
    add("zoo_ga_vs_cma", ["yardsticks"],
        "zoo GA against zoo CMA-ES, head to head, points per episode")(
        lambda d: _f(d["yardsticks"]["zoo_ga_vs_zoo_cma"]["mean"], 2, True))
    add("zoo_n", ["yardsticks"], "final champions scored against the zoo")(
        lambda d: str(len(d["yardsticks"]["per_run"])))
    add("zoo_games", ["yardsticks"], "games per champion and zoo opponent")(
        lambda d: str(2 * d["yardsticks"]["games_per_side"]))
    add("zoo_above_base", ["yardsticks", "per_run"],
        "final champions above parity against the 2015 baseline (held out)")(
        lambda d: str(sum(v > 0 for v in zoo_base(d).values())))
    add("zoo_best_vs_ga", ["yardsticks"],
        "best final champion against the zoo GA, points per episode")(
        lambda d: _f(max(zoo(d, "zoo-ga").values()), 2, True))
    add("zoo_valid_steps", ["yardsticks"],
        "steps compared bit for bit, compiled zoo games vs slimevolleygym")(
        lambda d: f"{sum(r['steps'] for r in d['yardsticks']['validation']):,}")
    add("zoo_valid_games", ["yardsticks"],
        "games compared bit for bit, compiled zoo games vs slimevolleygym")(
        lambda d: str(sum(r["games"] for r in d["yardsticks"]["validation"])))

    # ---- WP6: the preregistered replication -----------------------------
    def rp(d):
        return d["replication"]
    add("rep_runs", ["replication"], "replication: runs per condition")(
        lambda d: str(rp(d)["n"]["control"]))
    add("rep_total", ["replication"], "replication: runs in total")(
        lambda d: str(sum(rp(d)["n"].values())))
    add("rep_verdicts", ["replication"],
        "replication: claims replicated, of those tested")(
        lambda d: f"{sum(rp(d)['verdict'].values())} of {len(rp(d)['verdict'])}")
    add("rep_lag_first", ["replication"],
        "replication: control runs with the internal transition first, of the eligible")(
        lambda d: f"{rp(d)['H1']['positive']}/{rp(d)['H1']['informative']}")
    add("rep_ctrl_learned", ["replication"], "replication: control runs that learned to rally")(
        lambda d: f"{rp(d)['H2']['learned']}/{rp(d)['H2']['of']}")
    add("rep_timing_ratio", ["replication"],
        "replication: latest / earliest internal transition, control")(
        lambda d: _f(rp(d)["H2"]["timing_ratio"], 1))
    add("rep_rho", ["replication"], "replication: mean rho(Elo, time), control")(
        lambda d: _f(rp(d)["H3"]["rho_mean"], 2, True))
    add("rep_cyclic_pct", ["replication"],
        "replication: cyclic share of decided checkpoint triads, control, in %")(
        lambda d: _pct(rp(d)["H3"]["cyclic_share"], 1))
    add("rep_rank", ["replication"],
        "replication: mean rank of the exported individual in its pool of 128")(
        lambda d: f"{np.mean(rp(d)['H4']['a']['mean_rank']):.0f}")
    add("rep_rho_streak", ["replication"],
        "replication: mean rho(streak counter, skill)")(
        lambda d: _f(rp(d)["H4"]["b"]["rho_mean"], 2, True))
    add("rep_decl_exp", ["replication"],
        "replication: summed decline of the exported individual, control runs")(
        lambda d: _f(rp(d)["H4"]["c"]["sum_exported"], 1))
    add("rep_decl_best", ["replication"],
        "replication: summed decline of the pool's best member, control runs")(
        lambda d: _f(rp(d)["H4"]["c"]["sum_best"], 1))
    add("rep_parent_learned", ["replication"],
        "replication: archive-as-parent runs that learned to rally")(
        lambda d: f"{rp(d)['H5']['learned_parent']}/{rp(d)['H5']['of_parent']}")
    add("rep_test_learned", ["replication"],
        "replication: archive-as-test runs that learned to rally")(
        lambda d: f"{rp(d)['H6']['learned_test']}/{rp(d)['H6']['of_test']}")
    add("rep_archive_pmin", ["replication"],
        "replication: smallest of the four archive-as-test vs control p values")(
        lambda d: _f(min(c["p_two_sided"] for c in rp(d)["H6"]["comparisons"].values()), 2))
    add("rep_arch_learned_min", ["replication"],
        "replication: lowest late archive win rate, archive-as-test runs that learned")(
        lambda d: _f(min(rp(d)["H6"]["archive_late_learned"]), 2))
    add("rep_arch_learned_max", ["replication"],
        "replication: highest late archive win rate, runs that learned")(
        lambda d: _f(max(rp(d)["H6"]["archive_late_learned"]), 2))
    add("rep_arch_failed_min", ["replication"],
        "replication: lowest late archive win rate, archive-as-test runs that did not learn")(
        lambda d: _f(min(rp(d)["H6"]["archive_late_failed"]), 2))

    # ---- WP8: the discmix experiment (lab) ------------------------------
    def lab(d):
        return d["lab"]

    def lab_lams(d):
        return sorted(lab(d)["H8b"], key=float)
    add("lab_runs", ["lab"], "discmix experiment: runs in total")(
        lambda d: str(len(lab(d)["per_run"])))
    add("lab_lambda_max", ["lab"], "discmix experiment: largest lambda")(
        lambda d: _f(float(lab_lams(d)[-1]), 2))
    add("lab_cyc_hi_pct", ["lab"],
        "discmix: cyclic share of champion triads at the largest lambda, control, in %")(
        lambda d: _pct(lab(d)["H8a"]["control"]["share_by_lambda"][lab_lams(d)[-1]], 1))
    add("lab_cyc_mid_pct", ["lab"],
        "discmix: cyclic share of champion triads at lambda 0.5, control, in %")(
        lambda d: _pct(lab(d)["H8a"]["control"]["share_by_lambda"]["0.50"], 1))
    add("lab_cycle_rho", ["lab"],
        "discmix: Spearman rho(lambda, cyclic share), control runs")(
        lambda d: _f(lab(d)["H8a"]["control"]["rho"], 2, True))
    add("lab_rank_min", ["lab"],
        "discmix: lowest per-lambda mean rank of the exported individual (of 128)")(
        lambda d: f"{min(r['mean_rank'] for r in lab(d)['H8b'].values()):.0f}")
    add("lab_rank_max", ["lab"],
        "discmix: highest per-lambda mean rank of the exported individual (of 128)")(
        lambda d: f"{max(r['mean_rank'] for r in lab(d)['H8b'].values()):.0f}")
    add("lab_rho_streak_min", ["lab"],
        "discmix: lowest per-lambda mean rho(streak, true strength)")(
        lambda d: _f(min(r["mean_rho_streak"] for r in lab(d)["H8b"].values()), 2, True))
    add("lab_rho_streak_max", ["lab"],
        "discmix: highest per-lambda mean rho(streak, true strength)")(
        lambda d: _f(max(r["mean_rho_streak"] for r in lab(d)["H8b"].values()), 2, True))
    add("lab_decl_exp_hi", ["lab"],
        "discmix: exported individual's summed decline at the largest lambda")(
        lambda d: _f(lab(d)["H8b"][lab_lams(d)[-1]]["decline_exported"], 2))
    add("lab_decl_best_hi", ["lab"],
        "discmix: best member's summed decline at the largest lambda")(
        lambda d: _f(lab(d)["H8b"][lab_lams(d)[-1]]["decline_best"], 2))
    add("lab_trend_p", ["lab"],
        "discmix: one-sided p of the archive-effect trend over lambda")(
        lambda d: _f(lab(d)["H8c"]["p_one_sided"], 3))
    add("lab_delta_min", ["lab"],
        "discmix: most negative per-lambda archive-as-test effect (Cliff's delta)")(
        lambda d: _f(min(r["cliffs_delta"] for r in lab(d)["H8c"]["by_lambda"].values()), 2, True))
    add("lab_delta_low_max", ["lab"],
        "discmix: least negative archive effect among lambda <= 0.5")(
        lambda d: _f(max(r["cliffs_delta"] for l, r in lab(d)["H8c"]["by_lambda"].items()
                         if float(l) <= 0.5), 2, True))
    add("lab_p_low_min", ["lab"],
        "discmix: smallest per-lambda two-sided p of the archive effect, lambda <= 0.5")(
        lambda d: _f(min(r["p_two_sided"] for l, r in lab(d)["H8c"]["by_lambda"].items()
                         if float(l) <= 0.5), 3))
    add("lab_p_low_max", ["lab"],
        "discmix: largest per-lambda two-sided p of the archive effect, lambda <= 0.5")(
        lambda d: _f(max(r["p_two_sided"] for l, r in lab(d)["H8c"]["by_lambda"].items()
                         if float(l) <= 0.5), 3))

    # ---- WP9: an archive organised by behaviour (niche archive) ---------
    def qd(d):
        return d["qd"]

    def qd_slime(d, ref="vs_control"):
        return qd(d)["slime"][ref].values()

    def qd_lam(d):
        return qd(d)["discmix"]["by_lambda"].values()
    add("qd_capacity", ["qd"], "niche archive: slots (one per grid cell), from its protocol")(
        lambda d: str(json.load(open("results/qd/protocol.json"))["capacity"]))
    add("hoftest_capacity", ["qd"],
        "time-ordered archive as test (hof-eval-v2): slots, from the matrix protocol")(
        lambda d: str(json.load(open("results/matrix/protocol.json"))
                      ["conditions"]["hof-eval-v2"]["cap"]))
    add("qd_runs", ["qd"], "niche-archive experiment: runs in total")(
        lambda d: str(len(qd(d)["per_run"]["slime"]) // 3 + len(qd(d)["per_run"]["discmix"]) // 3))
    add("qd_slime_pmin", ["qd"],
        "niche archive, Slime Volleyball: smallest two-sided p of the four outcomes vs control")(
        lambda d: _f(min(c["p_two_sided"] for c in qd_slime(d)), 2))
    add("qd_slime_fifo_pmin", ["qd"],
        "niche archive, Slime Volleyball: smallest two-sided p of the four outcomes vs the "
        "time-ordered archive")(
        lambda d: _f(min(c["p_two_sided"] for c in qd_slime(d, "vs_fifo")), 2))
    add("qd_slime_learned", ["qd"],
        "niche archive, Slime Volleyball: runs that learned to rally")(
        lambda d: str(qd(d)["slime"]["learned"]["niche"]))
    add("qd_ctrl_learned", ["qd"],
        "niche experiment: control runs (same seeds) that learned to rally")(
        lambda d: str(qd(d)["slime"]["learned"]["control"]))
    add("qd_slime_n", ["qd"], "niche archive, Slime Volleyball: runs per arm")(
        lambda d: str(qd(d)["slime"]["n"]))
    add("qd_cells_min", ["qd"],
        "niche archive, Slime Volleyball: fewest occupied cells (of 64) at the end of a run")(
        lambda d: str(min(qd(d)["slime"]["archive_cells_final"])))
    add("qd_cells_max", ["qd"],
        "niche archive, Slime Volleyball: most occupied cells (of 64) at the end of a run")(
        lambda d: str(max(qd(d)["slime"]["archive_cells_final"])))
    add("qd_lab_cells_min", ["qd"],
        "niche archive, discmix: lowest per-lambda mean of occupied cells at the end")(
        lambda d: f"{min(r['archive_cells_final'] for r in qd_lam(d)):.0f}")
    add("qd_lab_cells_max", ["qd"],
        "niche archive, discmix: highest per-lambda mean of occupied cells at the end")(
        lambda d: f"{max(r['archive_cells_final'] for r in qd_lam(d)):.0f}")
    add("qd_trend_p", ["qd"],
        "niche archive, discmix: one-sided permutation p of the effect trend over lambda (H9b)")(
        lambda d: _f(qd(d)["discmix"]["H9b"]["p_one_sided"], 3))
    add("qd_top_p", ["qd"],
        "niche archive, discmix: one-sided p, niche vs time-ordered archive at the largest "
        "lambda (H9c)")(lambda d: _f(qd(d)["discmix"]["H9c"]["p_one_sided"], 2))
    add("qd_lab_delta_min", ["qd"],
        "niche archive, discmix: most negative per-lambda Cliff's delta vs control")(
        lambda d: _f(min(r["vs_control"]["cliffs_delta"] for r in qd_lam(d)), 2, True))
    add("qd_lab_delta_max", ["qd"],
        "niche archive, discmix: largest per-lambda Cliff's delta vs control")(
        lambda d: _f(max(r["vs_control"]["cliffs_delta"] for r in qd_lam(d)), 2, True))
    add("qd_lab_pmin", ["qd"],
        "niche archive, discmix: smallest per-lambda two-sided p, vs control or vs the "
        "time-ordered archive")(
        lambda d: _f(min(min(r["vs_control"]["p_two_sided"], r["vs_test"]["p_two_sided"])
                         for r in qd_lam(d)), 2))

    # ---- WP9: NEAT as a fifth family ------------------------------------
    def nt(d):
        return d["neat"]

    def nf(d, f="neat"):
        return nt(d)["families"][f]
    add("neat_runs", ["neat"], "NEAT: runs")(lambda d: str(nf(d)["runs"]))
    add("neat_learned", ["neat"], "NEAT: runs that learned to rally")(
        lambda d: str(nf(d)["learned"]))
    add("neat_parity", ["neat"], "NEAT: runs with a champion above parity")(
        lambda d: str(nf(d)["reached_parity"]))
    add("neat_final", ["neat"], "NEAT: mean final champion score, held out")(
        lambda d: _f(nf(d)["final_mean"], 2, True))
    add("neat_final_sd", ["neat"], "NEAT: s.d. over runs of the final champion score")(
        lambda d: _f(nf(d)["final_sd"], 2))
    add("neat_best_final", ["neat"], "NEAT: best final champion score of any run")(
        lambda d: _f(nf(d)["best_final"], 2, True))
    add("neat_ga_final", ["neat"],
        "generational GA: mean final champion score, held out (NEAT comparison)")(
        lambda d: _f(nf(d, "ga2015")["final_mean"], 2, True))
    add("neat_delta", ["neat"], "H9d: Cliff's delta, NEAT minus generational GA, final champion")(
        lambda d: _f(nt(d)["H9d"]["cliffs_delta"], 2, True))
    add("neat_p", ["neat"], "H9d: two-sided exact Mann-Whitney p")(
        lambda d: f"{nt(d)['H9d']['p_two_sided']:.4f}")
    add("neat_elo", ["neat"], "NEAT: median cross-run Elo of the final champions")(
        lambda d: f"{nf(d)['elo_median']:+.0f}")
    add("neat_elo_next", ["neat"],
        "lowest median cross-run Elo among the four other families")(
        lambda d: f"{min(nf(d, f)['elo_median'] for f in ('control', 'ga2015', 'es', 'hof-eval-v2')):+.0f}")
    add("neat_hidden_min", ["neat"], "NEAT: fewest hidden nodes of a final champion")(
        lambda d: str(min(nt(d)["structure"]["final_hidden"])))
    add("neat_hidden_max", ["neat"], "NEAT: most hidden nodes of a final champion")(
        lambda d: str(max(nt(d)["structure"]["final_hidden"])))
    add("neat_conn_min", ["neat"], "NEAT: fewest enabled connections of a final champion")(
        lambda d: str(min(nt(d)["structure"]["final_connections"])))
    add("neat_conn_max", ["neat"], "NEAT: most enabled connections of a final champion")(
        lambda d: str(max(nt(d)["structure"]["final_connections"])))
    add("neat_species", ["neat"], "NEAT: mean number of species over checkpoints and runs")(
        lambda d: _f(float(np.mean(nt(d)["structure"]["species_mean"])), 1))

    # ---- WP9: NEAT, exploratory follow-up (not preregistered) -----------
    def nx(d, v):
        return d["neat_explore"]["variants"][v]
    add("nx_runs", ["neat_explore"], "NEAT exploratory: runs per variant")(
        lambda d: str(nx(d, "as-ga")["runs"]))
    add("nx_mlp_learned", ["neat_explore"],
        "NEAT exploratory, started from the study's network: runs that learned")(
        lambda d: str(nx(d, "mlp-start")["learned"]))
    add("nx_noreset_learned", ["neat_explore"],
        "NEAT exploratory, no weight resets: runs that learned")(
        lambda d: str(nx(d, "no-reset")["learned"]))
    add("nx_asga_learned", ["neat_explore"],
        "NEAT exploratory, loop reduced towards the generational GA: runs that learned")(
        lambda d: str(nx(d, "as-ga")["learned"]))
    add("nx_asga_parity", ["neat_explore"],
        "NEAT exploratory, loop reduced towards the generational GA: runs above parity")(
        lambda d: str(nx(d, "as-ga")["reached_parity"]))
    add("nx_asga_best_final", ["neat_explore"],
        "NEAT exploratory, loop reduced towards the generational GA: best final champion")(
        lambda d: _f(nx(d, "as-ga")["best_final"], 2, True))
    add("nx_asga_t_internal", ["neat_explore"],
        "NEAT exploratory, as-ga: earliest game count with rallies above 1,500 steps")(
        lambda d: _games(min(r["t_internal"] for r in d["neat_explore"]["per_run"].values()
                             if r["variant"] == "as-ga" and r["t_internal"] is not None)))
    add("nx_neat_meanlen_max", ["neat_explore"],
        "NEAT exploratory, mlp-start and no-reset: longest final training rally (steps)")(
        lambda d: f"{max(nx(d, v)['max_train_meanlen'] for v in ('mlp-start', 'no-reset')):,.0f}")

    # ---- the export check re-scored on held-out episodes (proxy_heldout) --
    def ph(d, group="original"):
        return d["proxy_heldout"]["summary"][group]
    add("ph_episodes", ["proxy_heldout"], "episodes per member in the export check")(
        lambda d: str(d["proxy_heldout"]["proxy_episodes"]))
    add("ph_runs", ["proxy_heldout"], "held-out export check: original control runs")(
        lambda d: str(ph(d)["runs"]))
    add("ph_gap", ["proxy_heldout"],
        "held-out export check: best member minus exported, both re-scored held out "
        "(best chosen on the proxy episodes), mean over snapshots, original runs")(
        lambda d: _f(ph(d)["gap_heldout"], 2))
    add("ph_gap_selecting", ["proxy_heldout"],
        "the same gap on the proxy episodes that chose the best member (inflated)")(
        lambda d: _f(ph(d)["gap_selecting"], 2))
    add("ph_inflation", ["proxy_heldout"],
        "mean inflation of the best member's proxy score over its held-out re-score")(
        lambda d: _f(ph(d)["best_inflation"], 2))
    add("ph_retest_r", ["proxy_heldout"],
        "test-retest correlation of the per-member proxy scores, median over snapshots "
        "whose scores spread (s.d. > 0.2), original runs")(
        lambda d: _f(ph(d)["retest_r_learned_median"], 2))
    add("ph_level_exp", ["proxy_heldout"], "held-out level of the exported member, original runs")(
        lambda d: _f(ph(d)["level_heldout_exported"], 2, True))
    add("ph_level_best", ["proxy_heldout"], "held-out level of the best member, original runs")(
        lambda d: _f(ph(d)["level_heldout_best"], 2, True))
    add("ph_level_med", ["proxy_heldout"], "held-out level of the median member, original runs")(
        lambda d: _f(ph(d)["level_heldout_median"], 2, True))
    add("ph_decl_exp", ["proxy_heldout"],
        "summed held-out declines of the exported member, original runs")(
        lambda d: _f(ph(d)["declines_heldout_exported"], 1))
    add("ph_decl_best", ["proxy_heldout"],
        "summed held-out declines of the best member, original runs")(
        lambda d: _f(ph(d)["declines_heldout_best"], 1))
    add("ph_decl_med", ["proxy_heldout"],
        "summed held-out declines of the median member, original runs")(
        lambda d: _f(ph(d)["declines_heldout_median"], 1))
    add("ph_decl_ratio", ["proxy_heldout"],
        "held-out declines, exported over best member, original runs")(
        lambda d: _f(ph(d)["decline_ratio_heldout"], 1))
    add("ph_decl_runs", ["proxy_heldout"],
        "original runs in which the exported member declined more than the best (held out)")(
        lambda d: str(ph(d)["runs_exported_declines_more_heldout"]))
    add("ph_rep_runs", ["proxy_heldout"], "held-out export check: replication control runs")(
        lambda d: str(ph(d, "replication")["runs"]))
    add("ph_rep_decl_exp", ["proxy_heldout"],
        "summed held-out declines of the exported member, replication runs")(
        lambda d: _f(ph(d, "replication")["declines_heldout_exported"], 1))
    add("ph_rep_decl_best", ["proxy_heldout"],
        "summed held-out declines of the best member, replication runs")(
        lambda d: _f(ph(d, "replication")["declines_heldout_best"], 1))
    add("ph_rep_decl_runs", ["proxy_heldout"],
        "replication runs in which the exported member declined more than the best (held out)")(
        lambda d: str(ph(d, "replication")["runs_exported_declines_more_heldout"]))
    add("ph_rep_gap", ["proxy_heldout"], "held-out gap to the best member, replication runs")(
        lambda d: _f(ph(d, "replication")["gap_heldout"], 2))
    def ph_sign_p(d, group):
        rs = [r for r in d["proxy_heldout"]["per_run"].values() if r["group"] == group]
        return su.sign_test_greater([r["declines_heldout_exported"] - r["declines_heldout_best"]
                                     for r in rs])[2]
    add("ph_rep_decl_p", ["proxy_heldout"],
        "replication runs: one-sided exact sign test, exported declines more than the "
        "best member, held out")(lambda d: _f(ph_sign_p(d, "replication"), 3))
    add("ph_rep_level_exp", ["proxy_heldout"], "held-out level of the exported member, replication runs")(
        lambda d: _f(ph(d, "replication")["level_heldout_exported"], 2, True))
    add("ph_rep_level_med", ["proxy_heldout"], "held-out level of the median member, replication runs")(
        lambda d: _f(ph(d, "replication")["level_heldout_median"], 2, True))
    add("ph_x_gap", ["proxy_heldout"], "held-out gap to the best member, export-test runs")(
        lambda d: _f(ph(d, "export")["gap_heldout"], 2))
    add("ph_x_decl_runs", ["proxy_heldout"],
        "export-test runs in which the exported member declined more than the best (held out)")(
        lambda d: str(ph(d, "export")["runs_exported_declines_more_heldout"]))
    add("ph_x_runs", ["proxy_heldout"], "held-out export check: export-test control runs")(
        lambda d: str(ph(d, "export")["runs"]))
    # ---- C6 against the fresh control runs of the replication ------------
    def rep_rows(d, cond):
        return [r for n, r in d["replication"]["per_run"].items() if n.rsplit("_s", 1)[0] == cond]
    add("rep_ctrl_final_sd", ["replication"],
        "replication: s.d. of the end-of-run champion's held-out score, control runs")(
        lambda d: _f(float(np.std([r["final_holdout"] for r in rep_rows(d, "control")], ddof=1)), 2))
    add("rep_test_learned_n", ["replication"],
        "replication: archive-as-test runs that learned to rally")(
        lambda d: f"{sum(r['reached'] for r in rep_rows(d, 'hof-eval-v2'))}/{len(rep_rows(d, 'hof-eval-v2'))}")
    add("ctrl_final_sd", ["per_run"], "matrix: s.d. of the end-of-run champion's held-out score, control")(
        lambda d: _f(float(np.std([r["final_holdout"] for r in _rows(d["per_run"], "control")], ddof=1)), 2))
    add("fam_final_sd_min", ["per_run"],
        "matrix: smallest end-of-run s.d. among the generational GA, ES and archive as test")(
        lambda d: _f(min(float(np.std([r["final_holdout"] for r in _rows(d["per_run"], c)], ddof=1))
                         for c in ("ga2015", "es", "hof-eval-v2")), 2))
    add("fam_final_sd_max", ["per_run"],
        "matrix: largest end-of-run s.d. among the generational GA, ES and archive as test")(
        lambda d: _f(max(float(np.std([r["final_holdout"] for r in _rows(d["per_run"], c)], ddof=1))
                         for c in ("ga2015", "es", "hof-eval-v2")), 2))
    add("reexport_gain_sixteen", ["reexport"],
        "post hoc: level gain of the 16-peer round robin over the streak rule")(
        lambda d: _f(rx(d)["internal_score_16"]["level_mean"]
                     - rx(d)["streak_score"]["level_mean"], 2, True))
    add("reexport_gain_max", ["reexport"],
        "post hoc: level gain of the largest round robin over the streak rule")(
        lambda d: _f(rx(d)[maxkey({k: 0 for k in rx(d) if k.startswith("internal_score_")})]
                     ["level_mean"] - rx(d)["streak_score"]["level_mean"], 2, True))

    # ---- WP10: alternative export rules (preregistered) -----------------
    def xs(d):
        return d["export"]["slime"]

    def xmx(d):
        return d["export"]["discmix"]

    def xlam(d):
        return sorted(xmx(d)["by_lambda"], key=float)
    add("x_runs", ["export"], "export rules: fresh Slime Volleyball control runs")(
        lambda d: str(xs(d)["H10a"]["n"]))
    add("x_streak_level", ["export"],
        "export rules: level of the streak rule's exported members (held out)")(
        lambda d: _f(xs(d)["rules"]["streak"]["level"], 2, True))
    add("x_tourney_level", ["export"],
        "export rules: level of the 16-peer tournament's exported members (held out)")(
        lambda d: _f(xs(d)["rules"]["tournament-16"]["level"], 2, True))
    add("x_best_level", ["export"],
        "export rules: level of the best member (oracle)")(
        lambda d: _f(xs(d)["rules"]["best"]["level"], 2, True))
    add("x_gain", ["export"], "H10a: mean per-run gain, tournament-16 minus streak")(
        lambda d: _f(xs(d)["H10a"]["mean_gain"], 2, True))
    add("x_improved", ["export"], "H10a: runs in which tournament-16 exported better")(
        lambda d: str(xs(d)["H10a"]["runs_improved"]))
    add("x_p", ["export"], "H10a: one-sided exact sign-flip p")(
        lambda d: _f(xs(d)["H10a"]["p_one_sided"], 3))
    add("x_recovered_pct", ["export"],
        "export rules: share of the streak-to-best gap closed by tournament-16, in %")(
        lambda d: _pct(xs(d)["recovered_fraction"]["tournament-16"]))
    add("x_recovered_big_pct", ["export"],
        "export rules: share of the gap closed by the 64-peer tournament (descriptive), in %")(
        lambda d: _pct(xs(d)["recovered_fraction"]["tournament-64"]))
    add("x_decl_streak", ["export"], "export rules: mean summed declines, streak rule")(
        lambda d: _f(xs(d)["rules"]["streak"]["declines"], 2))
    add("x_decl_tourney", ["export"], "export rules: mean summed declines, tournament-16")(
        lambda d: _f(xs(d)["rules"]["tournament-16"]["declines"], 2))
    add("x_decl_big", ["export"],
        "export rules: mean summed declines, 64-peer tournament (descriptive)")(
        lambda d: _f(xs(d)["rules"]["tournament-64"]["declines"], 2))
    add("x_decl_improved", ["export"], "H10b: runs with fewer declines under tournament-16")(
        lambda d: str(xs(d)["H10b"]["runs_improved"]))
    add("x_decl_p", ["export"], "H10b: one-sided exact sign-flip p")(
        lambda d: _f(xs(d)["H10b"]["p_one_sided"], 2))
    add("x_rank_streak", ["export"],
        "export rules: mean rank of the streak rule's member in its population")(
        lambda d: f"{xs(d)['rules']['streak']['mean_rank']:.0f}")
    add("x_rank_tourney", ["export"],
        "export rules: mean rank of the tournament-16 member in its population")(
        lambda d: f"{xs(d)['rules']['tournament-16']['mean_rank']:.0f}")
    add("xm_improved", ["export"], "H10c: discmix runs in which tournament-16 did better")(
        lambda d: str(xmx(d)["H10c"]["runs_improved"]))
    add("xm_n", ["export"], "H10c: discmix runs")(lambda d: str(xmx(d)["H10c"]["n"]))
    add("xm_adv_low", ["export"],
        "discmix: tournament-16 advantage in outsider strength at the smallest lambda")(
        lambda d: _f(xmx(d)["by_lambda"][xlam(d)[0]]["advantage"], 2, True))
    add("xm_adv_high", ["export"],
        "discmix: tournament-16 advantage in outsider strength at the largest lambda")(
        lambda d: _f(xmx(d)["by_lambda"][xlam(d)[-1]]["advantage"], 2, True))
    add("xm_rho", ["export"], "H10d: Spearman rho(lambda, advantage)")(
        lambda d: _f(xmx(d)["H10d"]["rho"], 2, True))
    add("xm_trend_p", ["export"], "H10d: one-sided permutation p")(
        lambda d: _f(xmx(d)["H10d"]["p_one_sided"], 3))
    add("x_zoo_streak", ["export"],
        "export rules: final exported member (streak rule) against the zoo GA, mean")(
        lambda d: _f(xs(d)["zoo_final"]["streak"], 2, True))
    add("x_zoo_tourney", ["export"],
        "export rules: final exported member (tournament-16) against the zoo GA, mean")(
        lambda d: _f(xs(d)["zoo_final"]["tournament-16"], 2, True))
    add("x_zoo_tourney_lower", ["export"],
        "export rules: runs whose final tournament-16 member scored lower against the "
        "zoo GA than the streak rule's")(
        lambda d: str(sum(r["zoo_final"]["tournament-16"] < r["zoo_final"]["streak"]
                          for r in d["export"]["per_run"]["slime"].values())))

    def xr(d):
        return d["export_robustness"]
    add("xr_c_seeds", ["export_robustness"], "H10c by seed: seeds")(
        lambda d: str(xr(d)["H10c_by_seed"]["n_seeds"]))
    add("xr_c_improved", ["export_robustness"],
        "H10c by seed: seeds whose mean advantage over their four lambda runs is positive")(
        lambda d: str(xr(d)["H10c_by_seed"]["seeds_improved"]))
    add("xr_c_p", ["export_robustness"], "H10c by seed: one-sided exact sign-flip p")(
        lambda d: _sig(xr(d)["H10c_by_seed"]["p_one_sided"]))
    add("xr_d_p", ["export_robustness"],
        "H10d with lambda permuted only within seeds: one-sided p")(
        lambda d: _sig(xr(d)["H10d_within_seed"]["p_one_sided"]))

    # ---- WP13: why the streak counter fails (shadow counters) -----------
    def cs(d):
        return d["counter"]["summary"]

    def ct(d):
        return d["counter"]["tests"]

    def _pv(x):
        return _sig(x) if x < 0.001 else _f(x, 3)
    add("ctr_runs", ["counter"], "shadow counters: fresh control runs")(
        lambda d: str(cs(d)["n_runs"]))
    for key, rule, what in (("inh", "inherited", "Ha's counter"),
                            ("reset", "inherited-reset", "inherited, restarted at a tie"),
                            ("own", "own", "wins since birth"),
                            ("cur", "current", "the current genotype's wins"),
                            ("tour", "tournament-16", "the 16-peer tournament"),
                            ("med", "median", "the median member"),
                            ("best", "best", "the best member (oracle)")):
        add(f"ctr_level_{key}", ["counter"],
            f"shadow counters: held-out level of the members exported by {what}")(
            (lambda r: lambda d: _f(cs(d)["rules"][r]["level"], 2, True))(rule))
        add(f"ctr_rank_{key}", ["counter"],
            f"shadow counters: mean rank (of 128) of the member exported by {what}")(
            (lambda r: lambda d: f"{cs(d)['rules'][r]['rank']:.0f}")(rule))
    for key, rule in (("inh", "inherited"), ("reset", "inherited-reset"),
                      ("own", "own"), ("cur", "current")):
        add(f"ctr_rho_{key}", ["counter"],
            f"shadow counters: mean Spearman rho between the {rule} counter and skill")(
            (lambda r: lambda d: _f(cs(d)["rho"][r], 2, True))(rule))
        add(f"ctr_vol_{key}", ["counter"],
            f"shadow counters: volatility of the {rule} counter's reported curve "
            "(mean absolute change between checkpoints)")(
            (lambda r: lambda d: _f(cs(d)["curve"][r]["volatility"], 2))(rule))
        add(f"ctr_curve_decl_{key}", ["counter"],
            f"shadow counters: summed declines of the {rule} counter's reported curve, "
            "mean per run")(
            (lambda r: lambda d: _f(cs(d)["curve"][r]["declines"], 1))(rule))
    for h, k in (("H13a", "fix"), ("H13b", "volh"), ("H13c", "noinh"), ("H13d", "tie")):
        add(f"ctr_{k}_mean", ["counter"], f"{h}: mean per-run difference")(
            (lambda h: lambda d: _f(ct(d)[h]["mean"], 2, True))(h))
        add(f"ctr_{k}_runs", ["counter"], f"{h}: runs whose difference favours it")(
            (lambda h: lambda d: str(ct(d)[h]["runs_positive"]))(h))
        add(f"ctr_{k}_p", ["counter"], f"{h}: one-sided exact sign-flip p")(
            (lambda h: lambda d: _pv(ct(d)[h]["p_one_sided"]))(h))
    add("ctr_vs_tour", ["counter"],
        "shadow counters: current genotype's wins minus the 16-peer tournament, level")(
        lambda d: _f(ct(d)["current_vs_tournament"]["mean"], 2, True))
    add("ctr_vs_tour_runs", ["counter"],
        "shadow counters: runs in which the current genotype's wins beat the tournament")(
        lambda d: str(ct(d)["current_vs_tournament"]["runs_higher"]))
    add("ctr_vs_tour_p", ["counter"],
        "shadow counters: current genotype's wins vs the tournament, two-sided p")(
        lambda d: _pv(ct(d)["current_vs_tournament"]["p_two_sided"]))
    add("ctr_ties_late_pct", ["counter"],
        "shadow counters: share of tied games over the last 100,000 games, in %")(
        lambda d: _pct(cs(d)["diagnostics"]["tie_frac_late_mean"]))
    add("ctr_maxcount_inh", ["counter"],
        "shadow counters: median of Ha's counter's maximum over snapshots")(
        lambda d: f"{cs(d)['diagnostics']['max_count_median']['inherited']:,.0f}")
    add("ctr_maxcount_cur", ["counter"],
        "shadow counters: median of the current-genotype counter's maximum over snapshots")(
        lambda d: f"{cs(d)['diagnostics']['max_count_median']['current']:,.0f}")
    add("ctr_vol_drop_pct", ["counter"],
        "shadow counters: relative fall in curve volatility, current genotype's wins "
        "against Ha's counter, in %")(
        lambda d: _pct(1 - cs(d)["curve"]["current"]["volatility"]
                       / cs(d)["curve"]["inherited"]["volatility"]))
    add("ctr_tour_higher", ["counter"],
        "shadow counters: runs in which the 16-peer tournament exported a better member "
        "than the current genotype's wins")(
        lambda d: str(ct(d)["current_vs_tournament"]["n"]
                      - ct(d)["current_vs_tournament"]["runs_higher"]))
    add("ctr_spread_pct", ["counter"],
        "shadow counters: median gap between the largest and the median member's "
        "inherited count, as % of the largest")(
        lambda d: _pct(cs(d)["diagnostics"]["inherited_spread_median"], 1))

    # ---- WP7: transitivity at 5,000-game spacing ------------------------
    def fine(d, rule, c, n):
        rs = d["within_fine"]["runs"].values()
        return sum(r[rule][c] for r in rs), sum(r[rule][n] for r in rs)

    def fine_pct(d, rule, c, n, nd):
        k, m = fine(d, rule, c, n)
        return _pct(k / m, nd)
    add("fine_cyclic_deadband_pct", ["within_fine"],
        "5k spacing, control: cyclic share of decided triads, paper's +/-0.25 "
        "rule, pooled, in %")(lambda d: fine_pct(d, "deadband", "cyclic",
                                                 "triads_decided", 1))
    add("fine_short_deadband_pct", ["within_fine"],
        "5k spacing, control: cyclic share among triads within 50k games, "
        "paper's rule, pooled, in %")(lambda d: fine_pct(
            d, "deadband", "short_cyclic", "short_triads_decided", 1))
    add("fine_cyclic_sign", ["within_fine"],
        "5k spacing, control: cyclic triads under the sign-test rule, pooled")(
        lambda d: f"{fine(d, 'sign_test', 'cyclic', 'triads_decided')[0]:,}")
    add("fine_triads_sign", ["within_fine"],
        "5k spacing, control: decided triads under the sign-test rule, pooled")(
        lambda d: f"{fine(d, 'sign_test', 'cyclic', 'triads_decided')[1]:,}")
    add("fine_cyclic_sign_pct", ["within_fine"],
        "5k spacing, control: cyclic share of sign-test-decided triads, "
        "pooled, in %")(lambda d: fine_pct(d, "sign_test", "cyclic",
                                           "triads_decided", 2))
    add("fine_next_wins", ["within_fine"],
        "5k spacing, control: adjacent champions decided by the sign test in "
        "which the later one wins, k/n pooled")(
        lambda d: "{}/{}".format(*fine(d, "sign_test", "adjacent_later_wins",
                                       "adjacent_decided")))
    add("fine_next_wins_pct", ["within_fine"],
        "the same as a share, in %")(lambda d: fine_pct(
            d, "sign_test", "adjacent_later_wins", "adjacent_decided", 0))
    add("fine_rho_min", ["within_fine"],
        "5k spacing, control: lowest per-run rho(Elo, time)")(
        lambda d: _f(min(r["spearman_elo_vs_time"]
                         for r in d["within_fine"]["runs"].values()), 2, True))
    add("fine_games", ["within_fine"], "5k spacing: games per pair")(
        lambda d: str(d["within_fine"]["games_per_pair"]))

    # ---- inventory -------------------------------------------------------
    add("n_single_runs", ["per_run"], "single-population runs analysed")(
        lambda d: str(len(single(d))))
    add("n_runs_total", ["per_run"],
        "independent runs analysed (a two-population run counts once)")(
        lambda d: str(len(single(d)) + sum(len(x) for x in A(d).values())))
    return D


def compute(d):
    """{key: (value, deps)} for every number whose data is available."""
    out = {}
    with np.errstate(all="ignore"), warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        for key, (fn, deps, _doc) in definitions().items():
            if any(d.get(k) is None for k in deps):
                continue
            try:
                val = fn(d)
            except (KeyError, ValueError, IndexError, ZeroDivisionError):
                continue
            if "nan" in val or "inf" in val:    # e.g. an s.d. of one seed
                continue
            out[key] = (val, deps)
    return out


def tex_name(key):
    name = "n" + "".join(p.capitalize() for p in key.split("_"))
    # a LaTeX command name is letters only: \nRepC1 would define \nRepC
    if not name.isalpha():
        raise ValueError(f"number key {key!r} gives the macro name {name!r}, "
                         f"which LaTeX cannot define (letters only)")
    return name


def tex_value(s):
    # \ensuremath, so a signed value reads as a minus/plus sign both in text
    # and inside $...$
    s = s.replace("%", "\\%")
    if s[:1] in "+-" and s[1:2].isdigit():
        return f"\\ensuremath{{{s[0]}}}{s[1:]}"
    return s


def write_tex(values):
    lines = ["% generated by make_tables.py from prose_numbers.py -- do not edit by hand",
             "% every number in main.tex is one of these macros"]
    defs = definitions()
    for key in sorted(values):
        lines.append(f"\\newcommand{{\\{tex_name(key)}}}"
                     f"{{{tex_value(values[key][0])}}}"
                     f"  % {defs[key][2]}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import json
    from make_tables import FILES
    d = {k: (json.load(open(p)) if os.path.exists(p) else None)
         for k, p in FILES.items()}
    vals = compute(d)
    for key, (fn, deps, doc) in definitions().items():
        val = vals.get(key, ("(no data)",))[0]
        print(f"{key:<28} {val:>12}   {doc}")
