"""
prose_numbers.py — every number quoted in prose, generated from the analysis files.

Tables are generated by make_tables.py; the numbers in running text are
generated here. Markdown carries inline markers that are invisible when
rendered,

    rallies pass 1,500 steps at <!-- n:ref_t_internal -->104,200<!-- /n --> games

and make_tables.py rewrites what sits between them, exactly as it does for
tables: `--check` fails if a marker is stale or names a number nothing here
defines. paper/numbers.tex receives the same values as LaTeX macros
(ref_t_internal -> \\nRefTInternal), so README, write-up and paper cannot
disagree.

Each definition says which analysis files it reads, so make_tables.py can
verify their provenance before trusting the number.

    python prose_numbers.py    # print every number with its definition
"""

import glob
import os
import warnings

import numpy as np

import stats_utils as su

MATRIX = "results/matrix"

# Literature constant, not a result of this study: Ha's published score for
# the same GA at the same budget (slimevolleygym TRAINING.md, 1,000 episodes).
HA_PUBLISHED = 0.353

# readable names for conditions quoted in prose
FAMILY_LABEL = {"control": "2020 GA", "ga2015": "generational GA",
                "es": "self-play ES", "hof-eval-v2": "archive-as-test"}

# A two-population run ends in runaway dominance when one side wins more than
# this share of the cross-population games over the last 50,000 games.
RUNAWAY = 0.9
# ... measured over the last this-many checkpoints (as in make_tables table 10)
ASYM_LAST = 10


def _f(x, nd=2, sign=False):
    return f"{{:{'+' if sign else ''}.{nd}f}}".format(x)


def _games(x):
    return f"{int(x):,}"


def _frac(a, b):
    return f"{a}/{b}"


def _pct(x, nd=0):
    return f"{100 * x:.{nd}f}"


def _rows(per_run, cond):
    return [v for v in per_run.values() if v["condition"] == cond]


def _asym():
    """Outcome of every two-population run, read from the raw files."""
    runs = {}
    for f in sorted(glob.glob(os.path.join(MATRIX, "asym*_s*.npz"))):
        base, seed = os.path.basename(f)[:-4].rsplit("_s", 1)
        cond, side = base.rsplit("-", 1)
        runs.setdefault(cond, {}).setdefault(seed, {})[side] = np.load(f)
    out = {}
    for cond, seeds in runs.items():
        rows = []
        for seed, s in sorted(seeds.items()):
            ka = "strong" if "strong" in s else "a"
            kb = "weak" if "weak" in s else "b"
            if ka not in s or kb not in s:
                continue
            # cross-population win rate of the first (larger) side over the
            # last 50,000 games, and the best member of each pool at the end
            rows.append({"seed": int(seed),
                         "winrate": float(s[ka]["a_winrate"][-ASYM_LAST:].mean()),
                         "best_a": float(s[ka]["pop_best"][-1]),
                         "best_b": float(s[kb]["pop_best"][-1])})
        out[cond] = rows
    return out


# --------------------------------------------------------------------------
# Each entry: key -> (function of the loaded analysis files, files it reads,
# one-line definition). Keys use letters and underscores only, because they
# become LaTeX macro names.
# --------------------------------------------------------------------------
def definitions():
    D = {}

    def add(key, deps, doc):
        def deco(fn):
            D[key] = (fn, deps, doc)
            return fn
        return deco

    # ---- C1: the reference run -------------------------------------------
    add("ref_t_internal", ["reference"],
        "reference run: first game count at which self-play rallies exceed "
        "1,500 steps")(lambda d: _games(d["reference"]["t_internal"]))
    add("ref_t_parity", ["reference"],
        "reference run: first checkpoint scoring above 0 against the 2015 "
        "baseline")(lambda d: _games(d["reference"]["t_parity"]))
    add("ref_lag", ["reference"],
        "reference run: games between the two transitions")(
        lambda d: _games(d["reference"]["t_parity"]
                         - d["reference"]["t_internal"]))
    add("ref_peak_holdout", ["reference"],
        "reference run: best checkpoint, re-scored on the held-out seed")(
        lambda d: _f(d["reference"]["holdout"]["peak"]["mean"], 2, True))
    add("ref_final_holdout", ["reference"],
        "reference run: final checkpoint, re-scored on the held-out seed")(
        lambda d: _f(d["reference"]["holdout"]["final"]["mean"], 2, True))
    add("ha_published", [],
        "Ha (2020): published score of the same GA at the same budget "
        "(literature constant)")(lambda d: _f(HA_PUBLISHED, 2, True))

    # ---- C2: seed variance of the transition ---------------------------
    def t_int(d, which):
        v = d["conditions"]["conditions"]["control"]["t_internal"]
        return v[which]
    add("ctrl_runs", ["conditions"], "number of control seeds")(
        lambda d: str(d["conditions"]["conditions"]["control"]["n_runs"]))
    add("ctrl_t_internal_min", ["conditions"],
        "control: earliest internal transition across seeds")(
        lambda d: _games(t_int(d, "min")))
    add("ctrl_t_internal_max", ["conditions"],
        "control: latest internal transition across seeds")(
        lambda d: _games(t_int(d, "max")))
    add("ctrl_t_internal_median", ["conditions"],
        "control: median internal transition")(
        lambda d: _games(t_int(d, "median")))
    add("ctrl_t_internal_ratio", ["conditions"],
        "control: latest / earliest internal transition")(
        lambda d: _f(t_int(d, "max") / t_int(d, "min"), 1))

    def ctrl_cond(d, key, which):
        return d["conditions"]["conditions"]["control"][key][which]
    add("ctrl_t_parity_min", ["conditions"],
        "control: earliest first-above-parity checkpoint across seeds")(
        lambda d: _games(ctrl_cond(d, "t_parity", "min")))
    add("ctrl_t_parity_max", ["conditions"],
        "control: latest first-above-parity checkpoint across seeds")(
        lambda d: _games(ctrl_cond(d, "t_parity", "max")))
    add("ctrl_lag_min", ["conditions"],
        "control: shortest internal-to-external lag across seeds")(
        lambda d: _games(ctrl_cond(d, "lag_internal_to_parity", "min")))
    add("ctrl_lag_max", ["conditions"],
        "control: longest internal-to-external lag across seeds")(
        lambda d: _games(ctrl_cond(d, "lag_internal_to_parity", "max")))

    # ---- C3: transitivity --------------------------------------------------
    def within(d, cond):
        return [v for n, v in d["within"].items()
                if n.rsplit("_s", 1)[0] == cond]
    add("rho_within_ctrl", ["within"],
        "control: mean over seeds of Spearman rho(within-run Elo, training "
        "time)")(lambda d: _f(np.mean([v["spearman_elo_vs_time"]
                                       for v in within(d, "control")]), 2, True))
    add("cyclic_ctrl_pct", ["within"],
        "control: cyclic share of decided checkpoint triads, pooled, in %")(
        lambda d: _pct(sum(v["cyclic"] for v in within(d, "control"))
                       / max(1, sum(v["triads_decided"]
                                    for v in within(d, "control"))), 1))

    def learning_cyclic_max(d):
        # the largest cyclic share among conditions whose runs learned
        out = 0.0
        conds = d["conditions"]["conditions"]
        for c, a in conds.items():
            if a.get("n_reached", 0) < a["n_runs"]:
                continue
            rows = within(d, c)
            dec = sum(v["triads_decided"] for v in rows)
            if dec:
                out = max(out, sum(v["cyclic"] for v in rows) / dec)
        return out
    add("cyclic_learning_max_pct", ["within", "conditions"],
        "largest pooled cyclic share among conditions in which every run "
        "learned to rally, in %")(lambda d: _pct(learning_cyclic_max(d), 1))

    # ---- C4: the export rule ----------------------------------------------
    def proxy_rows(d):
        return [r for rows in d["proxy"].values() for r in rows]
    add("proxy_runs", ["proxy"], "control runs with population snapshots")(
        lambda d: str(len(d["proxy"])))
    add("proxy_pop", ["proxy"], "population size in the proxy check")(
        lambda d: str(proxy_rows(d)[0]["pop_size"]))
    add("proxy_rank_mean", ["proxy"],
        "mean rank of the exported individual in its own pool (1 = best), "
        "all snapshots")(lambda d: f"{np.mean([r['exported_rank'] + 1 for r in proxy_rows(d)]):.0f}")
    add("proxy_rho", ["proxy"],
        "mean Spearman rho(streak counter, score vs baseline) over snapshots")(
        lambda d: _f(np.mean([r["spearman_streak_vs_score"]
                              for r in proxy_rows(d)]), 2, True))
    add("proxy_gap", ["proxy"],
        "mean gap, best individual in the pool minus exported, points per "
        "episode")(lambda d: _f(np.mean([r["gap"] for r in proxy_rows(d)]), 2))

    def last_snap(d):
        t = max(r["tournament"] for r in proxy_rows(d))
        return [r for r in proxy_rows(d) if r["tournament"] == t]
    add("proxy_end_exported", ["proxy"],
        "final snapshot: mean score of the exported individual")(
        lambda d: _f(np.mean([r["exported_score"] for r in last_snap(d)]), 2, True))
    add("proxy_end_above", ["proxy"],
        "final snapshot: mean number of pool members above parity")(
        lambda d: f"{np.mean([r['n_above_parity'] for r in last_snap(d)]):.0f}")

    def rx(d):
        return d["reexport"]["summary"]
    add("reexport_rec_max", ["reexport"],
        "share of the exported-to-best gap closed by the largest internal "
        "round robin, in %")(lambda d: _pct(rx(d)["recovered_fraction"][
            max(rx(d)["recovered_fraction"], key=lambda k: int(k.split("_")[1]))]))
    add("reexport_peers_max", ["reexport"],
        "largest internal round robin: peers per individual")(
        lambda d: str(max(int(k.split("_")[1])
                          for k in rx(d)["recovered_fraction"])))
    add("reexport_streak_level", ["reexport"],
        "mean score of the streak-exported individual over all snapshots")(
        lambda d: _f(rx(d)["streak_score"]["level_mean"], 2, True))
    add("reexport_median_level", ["reexport"],
        "mean score of the population's median member over all snapshots")(
        lambda d: _f(rx(d)["median_score"]["level_mean"], 2, True))
    add("reexport_best_level", ["reexport"],
        "mean score of the best member (oracle) over all snapshots")(
        lambda d: _f(rx(d)["external_score"]["level_mean"], 2, True))
    add("reexport_rho_streak", ["reexport"],
        "rho(streak counter, true skill) in the re-export analysis")(
        lambda d: _f(rx(d)["rho_streak_external"], 2, True))
    add("reexport_games_max", ["reexport"],
        "ranking games per snapshot at the largest internal round robin")(
        lambda d: _games(rx(d)["ranking_games_per_snapshot"][
            max(rx(d)["ranking_games_per_snapshot"], key=lambda k: int(k.split("_")[1]))]))
    add("reexport_rho_max", ["reexport"],
        "rho(internal margin, true skill) at the largest round robin")(
        lambda d: _f(rx(d)["rho_internal_external"][
            max(rx(d)["rho_internal_external"], key=lambda k: int(k.split("_")[1]))], 2, True))

    # ---- C5: the archive -------------------------------------------------
    def cond(d, c):
        return d["conditions"]["conditions"][c]

    def hoftest_split(d, key, learned):
        return [r[key] for r in _rows(d["per_run"], "hof-eval-v2")
                if bool(r["reached"]) == learned]
    add("hoftest_n_failed", ["per_run"],
        "archive as test: runs that never learned to rally")(
        lambda d: str(len(hoftest_split(d, "hof_winrate_late", False))))
    add("hoftest_win_late_learned_min", ["per_run"],
        "archive as test, runs that learned: lowest late archive win rate")(
        lambda d: _f(min(hoftest_split(d, "hof_winrate_late", True)), 2))
    add("hoftest_win_late_learned_max", ["per_run"],
        "archive as test, runs that learned: highest late archive win rate")(
        lambda d: _f(max(hoftest_split(d, "hof_winrate_late", True)), 2))
    add("hoftest_win_late_failed", ["per_run"],
        "archive as test, runs that never learned: mean late archive win rate")(
        lambda d: _f(np.mean(hoftest_split(d, "hof_winrate_late", False)), 2))
    add("hoftest_skip_late_learned_min", ["per_run"],
        "archive as test, runs that learned: lowest late share of games "
        "without a selection event, in %")(
        lambda d: _pct(min(hoftest_split(d, "replacements_skipped_late", True))))
    add("hoftest_skip_late_learned_max", ["per_run"],
        "archive as test, runs that learned: highest late share of games "
        "without a selection event, in %")(
        lambda d: _pct(max(hoftest_split(d, "replacements_skipped_late", True))))
    add("hoftest_t_internal_median", ["conditions"],
        "archive as test: median internal transition of the runs that learned")(
        lambda d: _games(cond(d, "hof-eval-v2")["t_internal"]["median"]))
    def vs_ctrl(d, c, metric, field):
        return d["conditions"]["vs_control"][c][metric][field]

    def reached(d, c):
        a = cond(d, c)
        return _frac(a["n_reached"], a["n_runs"])
    for key, c in (("ctrl", "control"), ("hofparent", "hof-0.25"),
                   ("hoftest", "hof-eval-v2"), ("ga", "ga2015"),
                   ("es", "es")):
        add(f"{key}_reached", ["conditions"],
            f"{c}: runs whose population ever held 1,500-step rallies")(
            (lambda c: lambda d: reached(d, c))(c))
        add(f"{key}_parity", ["conditions"],
            f"{c}: runs with at least one checkpoint above parity")(
            (lambda c: lambda d: _frac(cond(d, c)["t_parity"]["reached"],
                                       cond(d, c)["n_runs"]))(c))
        add(f"{key}_final_mean", ["conditions"],
            f"{c}: mean end-of-run champion, held out")(
            (lambda c: lambda d: _f(cond(d, c)["final_holdout"]["mean"], 2, True))(c))
        add(f"{key}_peak_mean", ["conditions"],
            f"{c}: mean best champion, held out")(
            (lambda c: lambda d: _f(cond(d, c)["peak_holdout"]["mean"], 2, True))(c))
        add(f"{key}_above_pct", ["conditions"],
            f"{c}: mean share of checkpoints above parity, in %")(
            (lambda c: lambda d: _pct(cond(d, c)["above_parity"]["mean"]))(c))

    def reached_sum(d, conds):
        cc = d["conditions"]["conditions"]
        return (sum(cc[c]["n_reached"] for c in conds if c in cc),
                sum(cc[c]["n_runs"] for c in conds if c in cc))
    add("hofparent_other_reached", ["conditions"],
        "archive as parent at p = 0.5 or with a full-run archive: runs that "
        "learned to rally, pooled")(
        lambda d: _frac(*reached_sum(d, ("hof-0.50", "hof-full"))))
    for key, c in (("sigsmall", "sigma-0.05"), ("sigbig", "sigma-0.20")):
        add(f"{key}_reached", ["conditions"],
            f"{c}: runs that learned to rally")(
            (lambda c: lambda d: reached(d, c))(c))
        add(f"{key}_vol_reached_p", ["conditions"],
            f"{c} vs control, volatility over runs that learned: exact p")(
            (lambda c: lambda d: _f(vs_ctrl(d, c, "volatility_reached",
                                            "p_two_sided"), 3))(c))
        add(f"{key}_vol_reached_delta", ["conditions"],
            f"{c} vs control, volatility over runs that learned: Cliff's delta")(
            (lambda c: lambda d: _f(vs_ctrl(d, c, "volatility_reached",
                                            "cliffs_delta"), 2, True))(c))
        add(f"{key}_above_pct", ["conditions"],
            f"{c}: mean share of checkpoints above parity, in %")(
            (lambda c: lambda d: _pct(cond(d, c)["above_parity"]["mean"]))(c))
    add("hofparent_regress_pct", ["per_run"],
        "archive as parent: share of all games that copy an archived genome "
        "back into the pool (p x archive win rate), in %")(
        lambda d: _pct(np.mean([0.25 * r["hof_archive_winrate"]
                                for r in _rows(d["per_run"], "hof-0.25")]), 1))

    def hoftest(d, key):
        return [r[key] for r in _rows(d["per_run"], "hof-eval-v2")]
    add("hoftest_win_early_min", ["per_run"],
        "archive as test: lowest per-seed archive win rate, first 50,000 games")(
        lambda d: _f(min(hoftest(d, "hof_winrate_early")), 2))
    add("hoftest_win_early_max", ["per_run"],
        "archive as test: highest per-seed archive win rate, first 50,000 games")(
        lambda d: _f(max(hoftest(d, "hof_winrate_early")), 2))
    add("hoftest_win_late_min", ["per_run"],
        "archive as test: lowest per-seed archive win rate, last 50,000 games")(
        lambda d: _f(min(hoftest(d, "hof_winrate_late")), 2))
    add("hoftest_win_late_max", ["per_run"],
        "archive as test: highest per-seed archive win rate, last 50,000 games")(
        lambda d: _f(max(hoftest(d, "hof_winrate_late")), 2))
    add("hoftest_skip_late_min", ["per_run"],
        "archive as test: lowest per-seed share of games without a selection "
        "event, last 50,000 games, in %")(
        lambda d: _pct(min(hoftest(d, "replacements_skipped_late"))))
    add("hoftest_skip_late_max", ["per_run"],
        "archive as test: highest per-seed share of games without a selection "
        "event, last 50,000 games, in %")(
        lambda d: _pct(max(hoftest(d, "replacements_skipped_late"))))

    for metric in ("final_holdout", "peak_holdout", "above_parity",
                   "late_mean"):
        short = {"final_holdout": "final", "peak_holdout": "peak",
                 "above_parity": "above", "late_mean": "late"}[metric]
        add(f"hoftest_vs_ctrl_{short}_p", ["conditions"],
            f"archive as test vs control, {metric}: exact two-sided "
            f"Mann-Whitney p")((lambda m: lambda d: _f(
                vs_ctrl(d, "hof-eval-v2", m, "p_two_sided"), 3))(metric))
        add(f"hoftest_vs_ctrl_{short}_delta", ["conditions"],
            f"archive as test vs control, {metric}: Cliff's delta")(
            (lambda m: lambda d: _f(
                vs_ctrl(d, "hof-eval-v2", m, "cliffs_delta"), 2, True))(metric))

    # ---- C6: algorithm families ----------------------------------------
    def fh(d, c):
        return [r["final_holdout"] for r in _rows(d["per_run"], c)]
    for key, c in (("ga", "ga2015"), ("es", "es"), ("hoftest", "hof-eval-v2")):
        add(f"{key}_sd_ratio", ["per_run"],
            f"{c}: s.d. across seeds of the end-of-run champion (held out), "
            f"relative to the control's")(
            (lambda c: lambda d: _f(np.std(fh(d, c), ddof=1)
                                    / np.std(fh(d, "control"), ddof=1), 1))(c))

    def sd_ratios(d):
        return [np.std(fh(d, c), ddof=1) / np.std(fh(d, "control"), ddof=1)
                for c in ("ga2015", "es", "hof-eval-v2")]
    add("family_sd_ratio_min", ["per_run"],
        "smallest endpoint s.d. ratio (vs control) among the other three "
        "families")(lambda d: _f(min(sd_ratios(d)), 1))
    add("family_sd_ratio_max", ["per_run"],
        "largest endpoint s.d. ratio (vs control) among the other three "
        "families")(lambda d: _f(max(sd_ratios(d)), 1))

    def single(d):
        return [v for v in d["per_run"].values()
                if not v["condition"].startswith("asym")]
    add("best_endpoint", ["per_run"],
        "highest end-of-run champion (held out) of any single-population run")(
        lambda d: _f(max(v["final_holdout"] for v in single(d)), 2, True))
    add("best_endpoint_condition", ["per_run"],
        "condition of that run")(
        lambda d: max(single(d), key=lambda v: v["final_holdout"])["condition"])
    add("best_endpoint_label", ["per_run"],
        "readable name of the condition with the highest endpoint")(
        lambda d: FAMILY_LABEL.get(max(single(d), key=lambda v: v["final_holdout"])[
            "condition"], max(single(d), key=lambda v: v["final_holdout"])["condition"]))
    add("ctrl_best_endpoint", ["per_run"],
        "highest end-of-run champion (held out) among control seeds")(
        lambda d: _f(max(fh(d, "control")), 2, True))

    # ---- C7: unequal power (exploratory) --------------------------------
    def A(d):
        return _asym()
    add("asym_runs", ["per_run"], "two-population runs, all conditions")(
        lambda d: str(sum(len(v) for v in A(d).values())))
    add("asym_mutual", ["per_run"],
        "two-population runs whose BOTH pools end with a member above parity")(
        lambda d: str(sum(r["best_a"] > 0 and r["best_b"] > 0
                          for v in A(d).values() for r in v)))
    add("asym_one_sided", ["per_run"],
        "two-population runs where exactly one pool ends above parity")(
        lambda d: str(sum((r["best_a"] > 0) != (r["best_b"] > 0)
                          for v in A(d).values() for r in v)))
    add("asym_neither", ["per_run"],
        "two-population runs where neither pool ends above parity")(
        lambda d: str(sum(r["best_a"] <= 0 and r["best_b"] <= 0
                          for v in A(d).values() for r in v)))

    def runaway(r):
        return r["winrate"] > RUNAWAY or r["winrate"] < 1 - RUNAWAY
    add("asym_runaway", ["per_run"],
        "two-population runs ending in runaway dominance: cross-population "
        "win rate over the last 50,000 games above 0.9 or below 0.1")(
        lambda d: str(sum(runaway(r) for v in A(d).values() for r in v)))
    add("asym_runaway_sym", ["per_run"],
        "runaways in the symmetric control")(
        lambda d: str(sum(runaway(r) for r in A(d).get("asym1x", []))))
    for key, c in (("sym", "asym1x"), ("cap", "asym2x"),
                   ("norm", "asym2x-norm")):
        add(f"asym_{key}_lead", ["per_run"],
            f"{c}: runs in which the first (larger) side wins more than half "
            f"the cross-population games at the end")(
            (lambda c: lambda d: _frac(sum(r["winrate"] > 0.5 for r in A(d)[c]),
                                       len(A(d)[c])))(c))

    def asym_cmp(d, a, b, field):
        x = [r["winrate"] for r in A(d)[a]]
        y = [r["winrate"] for r in A(d)[b]]
        return su.compare(x, y)[field]
    for key, a, b in (("norm_vs_cap", "asym2x-norm", "asym2x"),
                      ("cap_vs_sym", "asym2x", "asym1x"),
                      ("norm_vs_sym", "asym2x-norm", "asym1x")):
        add(f"asym_{key}_p", ["per_run"],
            f"final win rate of the larger side, {a} vs {b}: exact two-sided "
            f"Mann-Whitney p")((lambda a, b: lambda d: _f(
                asym_cmp(d, a, b, "p_two_sided"), 3))(a, b))
        add(f"asym_{key}_delta", ["per_run"],
            f"final win rate of the larger side, {a} vs {b}: Cliff's delta")(
            (lambda a, b: lambda d: _f(asym_cmp(d, a, b, "cliffs_delta"),
                                       2, True))(a, b))

    # ---- the compiled environment ----------------------------------------
    def v(d):
        return d["validation"]
    add("val_games", ["validation"], "paired games in the bit-level check")(
        lambda d: _games(sum(x["n"] for x in v(d)["scenarios"].values())))
    add("val_steps", ["validation"], "environment steps compared")(
        lambda d: _games(sum(x["steps"] for x in v(d)["scenarios"].values())))
    add("val_ref_core_hours", ["validation"],
        "core-hours for one 500,000-game run at the reference implementation's "
        "measured games per second")(
        lambda d: f"{500_000 / v(d)['reference_games_per_sec'] / 3600:.0f}")
    add("val_speedup", ["validation"],
        "compiled / reference games per second on one core")(
        lambda d: f"{v(d)['speedup']:.0f}")

    # ---- design constants ----------------------------------------------
    # Read from the code and the recorded protocol that define them, so the
    # paper cannot describe a design other than the one that ran.
    import fastvolley as fv
    import run_experiments as rx_
    from math import comb

    def design(key, doc, fn):
        add(key, [], doc)(lambda d: fn())
    design("budget", "self-play games per run", lambda: _games(rx_.TOURNAMENTS))
    design("save_every", "games between exported checkpoints",
           lambda: _games(rx_.SAVE_EVERY))
    design("n_ckpt", "checkpoints per run",
           lambda: str(rx_.TOURNAMENTS // rx_.SAVE_EVERY))
    design("pop_every", "games between population snapshots",
           lambda: _games(rx_.POP_EVERY))
    design("sweep_episodes", "episodes per checkpoint in the sweep",
           lambda: _games(rx_.SWEEP_EPISODES))
    design("select_episodes", "episodes per held-out re-score",
           lambda: _games(rx_.SELECT_EPISODES))
    design("hof_every", "games between archive entries",
           lambda: _games(rx_.HOF_EVERY))
    design("pop", "population size of the control",
           lambda: str(rx_.CONDITIONS["control"]["pop"]))
    design("sigma", "mutation scale of the control",
           lambda: str(rx_.CONDITIONS["control"]["sigma"]))
    design("init_scale", "s.d. of the initial weights",
           lambda: str(rx_.INIT_SCALE))
    design("hof_p", "probability of an archive game, main archive conditions",
           lambda: str(rx_.CONDITIONS["hof-eval-v2"]["hof_prob"]))
    design("hof_cap_full", "archive capacity spanning the whole run",
           lambda: str(rx_.CONDITIONS["hof-eval-v2"]["cap"]))
    design("long_rally", "self-play rally length that counts as learned",
           lambda: _games(rx_.LONG_RALLY))
    import analyze_matrix as am
    design("late_window", "games in the late window of every metric",
           lambda: _games(am.WINDOW * rx_.SAVE_EVERY))
    design("hof_window", "games over which early and late archive win rates "
           "are averaged", lambda: _games(am.HOF_WINDOW))
    design("asym_window", "games over which the final cross-population win "
           "rate is averaged", lambda: _games(ASYM_LAST * rx_.SAVE_EVERY))
    design("param_count", "parameters of the evolved policy",
           lambda: str(fv.PARAM_COUNT))
    design("obs_size", "observation size", lambda: str(fv.OBS_SIZE))
    design("lives", "lives per side", lambda: str(fv.MAXLIVES))
    design("t_limit", "episode step limit", lambda: _games(fv.T_LIMIT))
    import asymmetric as az
    design("n_act", "buttons (network outputs)", lambda: str(az.N_ACT))
    design("hidden", "hidden units per layer, standard network",
           lambda: str(next(h for h in range(1, az.MAX_H + 1)
                            if az.param_count(h) == fv.PARAM_COUNT)))
    add("hidden_large", ["per_run"], "hidden units per layer, larger network")(
        lambda d: str(int(np.load(sorted(glob.glob(os.path.join(
            MATRIX, "asym2x-strong_s*.npz")))[0])["hidden"][0])))
    C = rx_.CONDITIONS
    design("ga_pop", "generational GA: population", lambda: str(C["ga2015"]["pop"]))
    design("ga_opponents", "generational GA: games per individual per generation",
           lambda: str(C["ga2015"]["n_opponents"]))
    design("ga_elite_pct", "generational GA: share retained per generation, in %",
           lambda: _pct(C["ga2015"]["n_elite"] / C["ga2015"]["pop"]))
    design("es_candidates", "self-play ES: mirrored perturbations per iteration",
           lambda: str(C["es"]["pop"]))
    design("sigma_small", "mutation-scale sweep: smaller sigma",
           lambda: _f(C["sigma-0.05"]["sigma"], 2))
    design("sigma_big", "mutation-scale sweep: larger sigma",
           lambda: _f(C["sigma-0.20"]["sigma"], 2))
    design("sigma_ctrl", "control sigma, two decimals",
           lambda: _f(C["control"]["sigma"], 2))
    design("pop_small", "population sweep: smaller population",
           lambda: str(C["pop-32"]["pop"]))
    design("pop_big", "population sweep: larger population (defined, never run)",
           lambda: str(C["pop-512"]["pop"]))
    design("seeds_main", "seeds of the conditions that carry a claim",
           lambda: str(len(rx_.SEEDS_MAIN)))
    design("min_p_six", "smallest attainable two-sided exact p with six runs "
           "a side", lambda: _f(2 / comb(12, 6), 3))
    design("runaway_cut", "win rate beyond which a two-population run is a "
           "runaway (and its complement)", lambda: _f(RUNAWAY, 1))
    design("runaway_pct", "runaway cut as a percentage of games",
           lambda: _pct(RUNAWAY))

    def runs_per_condition(d):
        n = {}
        for v in d["per_run"].values():
            c = v["condition"]
            c = c.rsplit("-", 1)[0] if c.startswith("asym") else c
            n.setdefault(c, set()).add(v["seed"])
        return [len(x) for x in n.values()]
    add("runs_min", ["per_run"], "fewest runs of any analysed condition")(
        lambda d: str(min(runs_per_condition(d))))
    add("runs_max", ["per_run"], "most runs of any analysed condition")(
        lambda d: str(max(runs_per_condition(d))))
    add("pop_small_runs", ["per_run"], "runs of the smaller population")(
        lambda d: str(len(_rows(d["per_run"], "pop-32"))))
    add("asym_param_large", ["per_run"], "parameters of the larger network")(
        lambda d: str(max(int(np.load(f)["param_count"][0]) for f in
                          glob.glob(os.path.join(MATRIX, "asym2x-strong_s*.npz")))))
    add("asym_cross", ["per_run"], "share of games crossing populations")(
        lambda d: str(float(np.load(sorted(glob.glob(os.path.join(
            MATRIX, "asym1x-a_s*.npz")))[0])["cross_prob"][0])))
    add("reexport_budget_pct", ["reexport"],
        "largest ranking budget as a share of one run's games, in %")(
        lambda d: _f(100 * max(rx(d)["ranking_games_per_snapshot"].values())
                     / rx_.TOURNAMENTS, 1))

    # ---- inventory -------------------------------------------------------
    add("n_single_runs", ["per_run"], "single-population runs analysed")(
        lambda d: str(len(single(d))))
    add("n_runs_total", ["per_run"],
        "independent runs analysed (a two-population run counts once)")(
        lambda d: str(len(single(d)) + sum(len(x) for x in A(d).values())))
    return D


def compute(d):
    """{key: (value, deps)} for every number whose data is available."""
    out = {}
    with np.errstate(all="ignore"), warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        for key, (fn, deps, _doc) in definitions().items():
            if any(d.get(k) is None for k in deps):
                continue
            try:
                val = fn(d)
            except (KeyError, ValueError, IndexError, ZeroDivisionError):
                continue
            if "nan" in val or "inf" in val:    # e.g. an s.d. of one seed
                continue
            out[key] = (val, deps)
    return out


def tex_name(key):
    return "n" + "".join(p.capitalize() for p in key.split("_"))


def tex_value(s):
    s = s.replace("%", "\\%")
    if s[:1] in "+-" and s[1:2].isdigit():
        return f"${s[0]}${s[1:]}"
    return s


def write_tex(values):
    lines = ["% generated by make_tables.py from prose_numbers.py -- do not edit by hand",
             "% every number in main.tex is one of these macros"]
    defs = definitions()
    for key in sorted(values):
        lines.append(f"\\newcommand{{\\{tex_name(key)}}}"
                     f"{{{tex_value(values[key][0])}}}"
                     f"  % {defs[key][2]}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import json
    from make_tables import FILES
    d = {k: (json.load(open(p)) if os.path.exists(p) else None)
         for k, p in FILES.items()}
    vals = compute(d)
    for key, (fn, deps, doc) in definitions().items():
        val = vals.get(key, ("(no data)",))[0]
        print(f"{key:<28} {val:>12}   {doc}")
